=== wargame-data/aos4/schema/hero.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://aos-data.org/schema/hero.schema.json",
  "title": "Hero",
  "description": "A hero warscroll for Age of Sigmar 4th Edition",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "id": {
      "type": "string",
      "pattern": "^[a-z0-9-]+$"
    },
    "name": {
      "type": "string"
    },
    "faction": {
      "type": "string",
      "pattern": "^[a-z0-9-]+$"
    },
    "grandAlliance": {
      "type": "string",
      "enum": [
        "order",
        "chaos",
        "death",
        "destruction"
      ]
    },
    "points": {
      "type": "integer",
      "minimum": 0
    },
    "stats": {
      "type": "object",
      "properties": {
        "move": {
          "type": "string",
          "pattern": "^(-|(\\d*D6(\\+\\d+)?|\\d+)\")$"
        },
        "health": {
          "type": "integer",
          "minimum": 1
        },
        "save": {
          "type": "string",
          "pattern": "^\\d\\+$"
        },
        "control": {
          "type": "integer",
          "minimum": 0
        }
      },
      "required": [
        "move",
        "health",
        "save",
        "control"
      ],
      "additionalProperties": false
    },
    "role": {
      "type": "string",
      "enum": [
        "battleline",
        "other",
        "artillery",
        "behemoth"
      ]
    },
    "keywords": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "regimentKeywords": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "baseSize": {
      "type": "integer",
      "minimum": 1
    },
    "maxSize": {
      "type": "integer",
      "minimum": 1
    },
    "canReinforce": {
      "type": "boolean"
    },
    "constraintModifiers": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "constraintId": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [
              "set",
              "increment",
              "decrement"
            ]
          },
          "value": {
            "type": "string"
          },
          "repeats": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "value": {
                  "type": "string"
                },
                "repeats": {
                  "type": "string"
                },
                "field": {
                  "type": "string"
                },
                "scope": {
                  "type": "string"
                },
                "childId": {
                  "type": "string"
                },
                "shared": {
                  "type": "boolean"
                },
                "roundUp": {
                  "type": "boolean"
                },
                "includeChildSelections": {
                  "type": "boolean"
                },
                "includeChildForces": {
                  "type": "boolean"
                },
                "percentValue": {
                  "type": "boolean"
                }
              },
              "required": [
                "value",
                "repeats",
                "field",
                "scope"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "constraintId",
          "type",
          "value"
        ],
        "additionalProperties": false
      }
    },
    "isCollective": {
      "type": "boolean"
    },
    "costs": {
      "type": "object",
      "properties": {
        "destinyPoints": {
          "type": "integer",
          "minimum": 0
        },
        "ptgCategory": {
          "type": "integer",
          "minimum": 0
        },
        "ghbCategory": {
          "type": "integer",
          "minimum": 0
        }
      },
      "additionalProperties": false
    },
    "rules": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "description"
        ],
        "additionalProperties": false
      }
    },
    "publication": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "shortName": {
          "type": "string"
        },
        "page": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ],
      "additionalProperties": false
    },
    "weapons": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [
              "melee",
              "ranged"
            ]
          },
          "range": {
            "type": "string",
            "pattern": "^\\d+\"$"
          },
          "attacks": {
            "anyOf": [
              {
                "type": "integer",
                "minimum": 1
              },
              {
                "type": "string",
                "pattern": "^\\d?[dD]\\d+.*$"
              }
            ]
          },
          "hit": {
            "type": "string",
            "pattern": "^\\d\\+$"
          },
          "wound": {
            "type": "string",
            "pattern": "^\\d\\+$"
          },
          "rend": {
            "type": "integer",
            "minimum": 0,
            "maximum": 4
          },
          "damage": {
            "anyOf": [
              {
                "type": "integer",
                "minimum": 1
              },
              {
                "type": "string",
                "pattern": "^\\d?[dD]\\d+.*$"
              },
              {
                "type": "string",
                "pattern": "^⟝.*⟞$"
              }
            ]
          },
          "abilities": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "name",
          "type",
          "attacks",
          "hit",
          "wound",
          "rend",
          "damage"
        ],
        "additionalProperties": false
      }
    },
    "abilities": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [
              "passive",
              "reaction",
              "once-per-turn",
              "once-per-battle",
              "spell",
              "prayer",
              "command"
            ]
          },
          "phase": {
            "type": "string",
            "enum": [
              "any",
              "hero",
              "movement",
              "shooting",
              "charge",
              "combat",
              "end"
            ]
          },
          "castingValue": {
            "type": "integer",
            "minimum": 2,
            "maximum": 12
          },
          "chantingValue": {
            "type": "integer",
            "minimum": 2,
            "maximum": 6
          },
          "declare": {
            "type": "string"
          },
          "effect": {
            "type": "string"
          },
          "keywords": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "color": {
            "type": "string",
            "enum": [
              "Black",
              "Blue",
              "Gray",
              "Green",
              "Orange",
              "Purple",
              "Red",
              "Yellow"
            ]
          },
          "abilityCategory": {
            "type": "string",
            "enum": [
              "Offensive",
              "Defensive",
              "Movement",
              "Control",
              "Special",
              "Rallying",
              "Shooting"
            ]
          },
          "modifiers": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "enum": [
                    "set",
                    "increment",
                    "decrement",
                    "append",
                    "add",
                    "remove"
                  ]
                },
                "field": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                },
                "conditions": {
                  "type": "object",
                  "properties": {
                    "logic": {
                      "type": "string",
                      "enum": [
                        "and",
                        "or"
                      ]
                    },
                    "conditions": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "type": {
                            "type": "string",
                            "enum": [
                              "equalTo",
                              "notEqualTo",
                              "lessThan",
                              "greaterThan",
                              "atLeast",
                              "atMost",
                              "instanceOf"
                            ]
                          },
                          "value": {
                            "type": "string"
                          },
                          "field": {
                            "type": "string"
                          },
                          "scope": {
                            "type": "string"
                          },
                          "childId": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "type",
                          "value",
                          "field"
                        ],
                        "additionalProperties": false
                      }
                    },
                    "groups": {
                      "type": "array",
                      "items": {}
                    }
                  },
                  "required": [
                    "logic"
                  ],
                  "additionalProperties": false
                }
              },
              "required": [
                "type",
                "field",
                "value"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "name",
          "type",
          "effect"
        ],
        "additionalProperties": false
      }
    },
    "notes": {
      "type": "string"
    },
    "isWizard": {
      "anyOf": [
        {
          "type": "integer",
          "minimum": 1
        },
        {
          "type": "null"
        }
      ]
    },
    "isPriest": {
      "anyOf": [
        {
          "type": "integer",
          "minimum": 1
        },
        {
          "type": "null"
        }
      ]
    },
    "isUnique": {
      "type": "boolean"
    },
    "regimentAllows": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "keywords": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "keywords",
          "description"
        ],
        "additionalProperties": false
      }
    },
    "canJoinRegiment": {
      "anyOf": [
        {
          "type": "object",
          "properties": {
            "keywords": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "keywords"
          ],
          "additionalProperties": false
        },
        {
          "type": "null"
        }
      ]
    },
    "_meta": {
      "type": "object",
      "properties": {
        "lastUpdated": {
          "type": "string"
        },
        "source": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "id",
    "name",
    "faction",
    "points",
    "stats",
    "role",
    "keywords",
    "baseSize",
    "weapons",
    "isWizard",
    "isPriest",
    "isUnique",
    "canJoinRegiment"
  ],
  "additionalProperties": false
}

=== wargame-data/aos4/data/factions/ogor-mawtribes/heroes/huskard-on-thundertusk.json
{
  "$schema": "https://aos-data.org/schema/hero.schema.json",
  "id": "huskard-on-thundertusk",
  "name": "Huskard on Thundertusk",
  "faction": "ogor-mawtribes",
  "points": 250,
  "stats": {
    "move": "10\"",
    "health": 14,
    "save": "4+",
    "control": 10
  },
  "role": "other",
  "keywords": [
    "BEASTCLAW RAIDERS",
    "DESTRUCTION",
    "HERO",
    "MONSTER",
    "OGOR",
    "OGOR MAWTRIBES",
    "PRIEST (1)"
  ],
  "baseSize": 1,
  "weapons": [
    {
      "name": "Ice Blast",
      "type": "ranged",
      "attacks": 1,
      "hit": "4+",
      "wound": "2+",
      "rend": 1,
      "damage": "D3+2",
      "range": "12\"",
      "abilities": [
        "Companion"
      ]
    },
    {
      "name": "Thundertusk’s Colossal Tusks",
      "type": "melee",
      "attacks": 3,
      "hit": "4+",
      "wound": "2+",
      "rend": 1,
      "damage": 5,
      "abilities": [
        "Anti-**^^Infantry^^** (+1 Rend)",
        "Companion"
      ]
    },
    {
      "name": "Punches and Kicks",
      "type": "melee",
      "attacks": 3,
      "hit": "4+",
      "wound": "2+",
      "rend": 0,
      "damage": 1
    },
    {
      "name": "Harpoon Launcher",
      "type": "ranged",
      "attacks": 1,
      "hit": "4+",
      "wound": "3+",
      "rend": 1,
      "damage": "D3",
      "range": "18\""
    },
    {
      "name": "Chaintrap",
      "type": "ranged",
      "attacks": 1,
      "hit": "4+",
      "wound": "3+",
      "rend": 1,
      "damage": 3,
      "range": "12\"",
      "abilities": [
        "Anti‑**^^Monster^^** (+1 Rend)"
      ]
    },
    {
      "name": "Blood Vulture",
      "type": "ranged",
      "attacks": 1,
      "hit": "2+",
      "wound": "3+",
      "rend": 0,
      "damage": 1,
      "range": "24\""
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-08",
    "source": "BSData import"
  },
  "grandAlliance": "destruction",
  "regimentKeywords": [
    "BEASTCLAW RAIDERS",
    "OGOR",
    "OGOR MAWTRIBES",
    "PRIEST (1)"
  ],
  "abilities": [
    {
      "name": "Battle Damaged",
      "type": "passive",
      "effect": "While this unit has 10 or more damage points, the Attacks characteristic of its **Thundertusk’s Colossal Tusks** is 2.",
      "color": "Black"
    },
    {
      "name": "Freezing Aura",
      "type": "once-per-turn",
      "effect": "Roll a dice. Add 1 to the roll if the target had **^^Strike-last^^** as a result of this ability in the previous turn. On a 4+, the target has **^^Strike-last^^** for the rest of the turn.",
      "phase": "combat",
      "declare": "Pick an enemy **^^Infantry^^** unit in combat with this unit to be the target.",
      "keywords": [
        "**^^RAMPAGE^^**"
      ],
      "color": "Red",
      "abilityCategory": "Defensive"
    }
  ],
  "publication": {
    "name": "Faction Pack: Ogor Mawtribes"
  },
  "isWizard": null,
  "isPriest": 1,
  "isUnique": false,
  "canJoinRegiment": null
}

=== wargame-data/aos4/data/factions/gloomspite-gitz/heroes/madcap-shaman.json
{
  "$schema": "https://aos-data.org/schema/hero.schema.json",
  "id": "madcap-shaman",
  "name": "Madcap Shaman",
  "faction": "gloomspite-gitz",
  "points": 80,
  "stats": {
    "move": "5\"",
    "health": 4,
    "save": "6+",
    "control": 2
  },
  "role": "other",
  "keywords": [
    "DESTRUCTION",
    "GLOOMSPITE GITZ",
    "HERO",
    "INFANTRY",
    "LEGENDS",
    "MOONCLAN",
    "WIZARD (1)"
  ],
  "baseSize": 1,
  "weapons": [
    {
      "name": "Moon Staff",
      "type": "melee",
      "attacks": 3,
      "hit": "4+",
      "wound": "4+",
      "rend": 1,
      "damage": "D3"
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-07",
    "source": "BSData import"
  },
  "grandAlliance": "destruction",
  "regimentKeywords": [
    "GLOOMSPITE GITZ",
    "LEGENDS",
    "MOONCLAN",
    "WIZARD (1)"
  ],
  "abilities": [
    {
      "name": "Madcap Mushroom",
      "type": "once-per-battle",
      "effect": "For the rest of the turn:\n• Add 1 to this unit’s power level.\n• If 2 or more dice in a casting roll for this unit have the same value, inflict D3 mortal damage on this unit after the **^^Spell^^** ability has been resolved.",
      "phase": "hero",
      "color": "Purple",
      "abilityCategory": "Offensive"
    }
  ],
  "publication": {
    "name": "Warhammer Legends"
  },
  "isWizard": 1,
  "isPriest": null,
  "isUnique": false,
  "canJoinRegiment": null,
  "regimentAllows": [
    {
      "keywords": [
        "MOONCLAN"
      ],
      "description": "Units with MOONCLAN keyword"
    }
  ]
}

=== wargame-data/aos4/data/factions/slaves-to-darkness/heroes/archaon-the-everchosen.json
{
  "$schema": "https://aos-data.org/schema/hero.schema.json",
  "id": "archaon-the-everchosen",
  "name": "Archaon, the Everchosen",
  "faction": "slaves-to-darkness",
  "points": 810,
  "stats": {
    "move": "14\"",
    "health": 25,
    "save": "3+",
    "control": 10
  },
  "role": "other",
  "keywords": [
    "CHAOS",
    "DAEMON",
    "FLY",
    "HERO",
    "MONSTER",
    "SLAVES TO DARKNESS",
    "UNIQUE",
    "WARD (5+)",
    "WARMASTER",
    "WARRIORS OF CHAOS",
    "WIZARD (2)"
  ],
  "baseSize": 1,
  "weapons": [
    {
      "name": "The Slayer of Kings",
      "type": "melee",
      "attacks": 4,
      "hit": "2+",
      "wound": "3+",
      "rend": 2,
      "damage": 3,
      "abilities": [
        "Anti-**^^Hero^^** (+1 Rend)"
      ]
    },
    {
      "name": "Dorghar’s Heads",
      "type": "melee",
      "attacks": 3,
      "hit": "3+",
      "wound": "2+",
      "rend": 1,
      "damage": 5,
      "abilities": [
        "Companion"
      ]
    },
    {
      "name": "Dorghar’s Claws and Tails",
      "type": "melee",
      "attacks": 6,
      "hit": "4+",
      "wound": "2+",
      "rend": 2,
      "damage": 3,
      "abilities": [
        "Companion"
      ]
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-08",
    "source": "BSData import"
  },
  "grandAlliance": "chaos",
  "regimentKeywords": [
    "DAEMON",
    "FLY",
    "SLAVES TO DARKNESS",
    "WARD (5+)",
    "WARRIORS OF CHAOS",
    "WIZARD (2)"
  ],
  "abilities": [
    {
      "name": "Battle Damaged",
      "type": "passive",
      "effect": "While this unit has 10 or more damage points, the Attacks characteristic of **Dorghar’s Claws and Tails** is 4.",
      "color": "Black"
    },
    {
      "name": "The Slayer of Kings",
      "type": "passive",
      "effect": "Each time this unit uses a **^^Fight^^** ability, if the unmodified wound roll for 2 or more attacks made with **The Slayer of Kings** that target the same **^^Hero^^** is 6, that **^^Hero^^** is automatically destroyed.",
      "color": "Red",
      "abilityCategory": "Offensive"
    },
    {
      "name": "The Eye of Sheerian",
      "type": "once-per-battle",
      "effect": "Roll a dice. This roll replaces the priority roll of the next battle round. On a 1-3, your opponent must take the first turn of that battle round. On a 4-6, you must take the first turn of that battle round. This ability cannot be used if there is an enemy **Archaon** on the battlefield.",
      "phase": "hero",
      "color": "Yellow",
      "abilityCategory": "Special"
    },
    {
      "name": "Three-headed Titan",
      "type": "once-per-turn",
      "effect": "Pick 1 of the following effects:\n***Filth-spewer:*** Pick an enemy unit within 6\" of this unit and roll a number of dice equal to the number of models in that unit, to a maximum of 7. For each 3+, inflict 1 mortal damage on that unit.\n***Skull-gorger:*** Pick an enemy unit in combat with this unit and roll a dice. If the roll exceeds that unit’s Health characteristic, 1 model in that unit is slain and you can **Heal (X)** this unit, where **X** is that unit’s Health characteristic.\n***Spell-eater:*** Pick a **^^Manifestation^^** within 12\" of this unit and roll a dice. On a 2+, it is banished and removed from play. In addition, inflict D3 mortal damage on the unit that summoned it.",
      "phase": "combat",
      "keywords": [
        "**^^RAMPAGE^^**"
      ],
      "color": "Red",
      "abilityCategory": "Special"
    }
  ],
  "publication": {
    "name": "Battletome: Slaves to Darkness"
  },
  "isWizard": 2,
  "isPriest": null,
  "isUnique": true,
  "canJoinRegiment": null
}

=== wargame-data/aos4/data/factions/kruleboyz/heroes/killaboss-on-great-gnashtoof.json
{
  "$schema": "https://aos-data.org/schema/hero.schema.json",
  "id": "killaboss-on-great-gnashtoof",
  "name": "Killaboss on Great Gnashtoof",
  "faction": "kruleboyz",
  "points": 150,
  "stats": {
    "move": "10\"",
    "health": 10,
    "save": "3+",
    "control": 2
  },
  "role": "other",
  "keywords": [
    "CAVALRY",
    "DESTRUCTION",
    "HERO",
    "KRULEBOYZ"
  ],
  "baseSize": 1,
  "weapons": [
    {
      "name": "Boss-stikka",
      "type": "melee",
      "attacks": 1,
      "hit": "4+",
      "wound": "4+",
      "rend": 0,
      "damage": 1,
      "abilities": [
        "Crit (Mortal)"
      ]
    },
    {
      "name": "Great Gnashtoof’s Jaws",
      "type": "melee",
      "attacks": 1,
      "hit": "4+",
      "wound": "4+",
      "rend": 0,
      "damage": 1,
      "abilities": [
        "Companion"
      ]
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-06",
    "source": "BSData import"
  },
  "grandAlliance": "destruction",
  "regimentKeywords": [
    "KRULEBOYZ"
  ],
  "abilities": [
    {
      "name": "That's Ours, Ya Gitz",
      "type": "passive",
      "effect": "While this unit is contesting an objective you do not control, add 1 to hit rolls for combat attacks made by friendly **^^Kruleboyz^^** units wholly within 12\" of this unit.",
      "color": "Red",
      "abilityCategory": "Offensive"
    },
    {
      "name": "All Part of da Plan",
      "type": "passive",
      "effect": "Add 3 to the target’s control score until the start of your next turn.",
      "phase": "hero",
      "declare": "Pick another friendly **^^Kruleboyz^^** unit wholly within 9\" of this unit to be the target.",
      "color": "Yellow",
      "abilityCategory": "Control"
    }
  ],
  "publication": {
    "name": "Battletome: Orruk Warclans"
  },
  "isWizard": null,
  "isPriest": null,
  "isUnique": false,
  "canJoinRegiment": null
}

=== wargame-data/aos4/data/factions/stormcast-eternals/heroes/knight-heraldor.json
{
  "$schema": "https://aos-data.org/schema/hero.schema.json",
  "id": "knight-heraldor",
  "name": "Knight-Heraldor",
  "faction": "stormcast-eternals",
  "points": 110,
  "stats": {
    "move": "5\"",
    "health": 6,
    "save": "3+",
    "control": 2
  },
  "role": "other",
  "keywords": [
    "HERO",
    "INFANTRY",
    "LEGENDS",
    "ORDER",
    "STORMCAST ETERNALS",
    "WARRIOR CHAMBER"
  ],
  "baseSize": 1,
  "weapons": [
    {
      "name": "Sigmarite Broadsword",
      "type": "melee",
      "attacks": 1,
      "hit": "3+",
      "wound": "4+",
      "rend": 0,
      "damage": 1
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-07",
    "source": "BSData import"
  },
  "grandAlliance": "order",
  "regimentKeywords": [
    "LEGENDS",
    "STORMCAST ETERNALS",
    "WARRIOR CHAMBER"
  ],
  "abilities": [
    {
      "name": "Thunderblast",
      "type": "passive",
      "effect": "Roll a dice. On a 2+, inflict an amount of mortal damage on the target equal to the roll.",
      "phase": "shooting",
      "declare": "Pick a visible faction terrain feature within 18\" of this unit to be the target.",
      "color": "Blue",
      "abilityCategory": "Shooting"
    },
    {
      "name": "Call to Battle",
      "type": "passive",
      "effect": "If a friendly **^^Warrior Chamber^^** unit wholly within 12\" of this unit uses the ‘Rally’ command, you can make 3 additional rally rolls of D6.",
      "color": "Yellow",
      "abilityCategory": "Rallying"
    }
  ],
  "publication": {
    "name": "Battletome Supplement: Stormcast Eternals"
  },
  "isWizard": null,
  "isPriest": null,
  "isUnique": false,
  "canJoinRegiment": null,
  "regimentAllows": [
    {
      "keywords": [
        "WARRIOR CHAMBER"
      ],
      "description": "Units with WARRIOR CHAMBER keyword"
    }
  ]
}

=== wargame-data/aos4/data/factions/idoneth-deepkin/heroes/eidolon-of-mathlann-aspect-of-the-sea.json
{
  "$schema": "https://aos-data.org/schema/hero.schema.json",
  "id": "eidolon-of-mathlann-aspect-of-the-sea",
  "name": "Eidolon of Mathlann, Aspect of the Sea",
  "faction": "idoneth-deepkin",
  "points": 340,
  "stats": {
    "move": "10\"",
    "health": 12,
    "save": "3+",
    "control": 5
  },
  "role": "other",
  "keywords": [
    "AELF",
    "EIDOLON",
    "FLY",
    "HERO",
    "IDONETH DEEPKIN",
    "MONSTER",
    "ORDER",
    "WARD (5+)",
    "WIZARD (2)"
  ],
  "baseSize": 1,
  "weapons": [
    {
      "name": "Blasts of Abyssal Energy",
      "type": "ranged",
      "attacks": 1,
      "hit": "3+",
      "wound": "4+",
      "rend": 0,
      "damage": 1,
      "range": "12\""
    },
    {
      "name": "Psi-trident and Deep-sea Sceptre",
      "type": "melee",
      "attacks": 1,
      "hit": "3+",
      "wound": "4+",
      "rend": 0,
      "damage": 1
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-06",
    "source": "BSData import"
  },
  "grandAlliance": "order",
  "regimentKeywords": [
    "AELF",
    "EIDOLON",
    "FLY",
    "IDONETH DEEPKIN",
    "WARD (5+)",
    "WIZARD (2)"
  ],
  "abilities": [
    {
      "name": "Dormant Energies",
      "type": "passive",
      "effect": "Add 1 to casting rolls for this unit.",
      "color": "Yellow",
      "abilityCategory": "Special"
    },
    {
      "name": "Tranquillity of the Abyss",
      "type": "passive",
      "effect": "Ignore negative modifiers to the control scores of friendly **^^Idoneth Deepkin^^** units while they are wholly within 12\" of this unit.",
      "color": "Purple",
      "abilityCategory": "Control"
    },
    {
      "name": "Vengeful Waves",
      "type": "once-per-turn",
      "effect": "Roll a dice. On a 3+, the target cannot use commands for the rest of the turn.",
      "phase": "charge",
      "declare": "If this unit has not charged this turn, pick an enemy unit in combat with it to be the target.",
      "keywords": [
        "**^^RAMPAGE^^**"
      ],
      "color": "Orange",
      "abilityCategory": "Special"
    },
    {
      "name": "Tsunami of Terror",
      "type": "spell",
      "effect": "Subtract 1 from save rolls for combat attacks that target those units until the start of your next turn.",
      "phase": "hero",
      "declare": "Pick up to 3 different visible enemy units within 12\" of this unit to be the targets, then make a casting roll of 2D6.",
      "castingValue": 7,
      "keywords": [
        "**^^SPELL^^**"
      ],
      "color": "Yellow",
      "abilityCategory": "Offensive"
    }
  ],
  "publication": {
    "name": "Battletome: Idoneth Deepkin"
  },
  "isWizard": 2,
  "isPriest": null,
  "isUnique": false,
  "canJoinRegiment": null
}
