=== wargame-data/aos4/schema/hero.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://aos-data.org/schema/hero.schema.json",
  "title": "Hero",
  "description": "A hero warscroll for Age of Sigmar 4th Edition",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "id": {
      "type": "string",
      "pattern": "^[a-z0-9-]+$"
    },
    "name": {
      "type": "string"
    },
    "faction": {
      "type": "string",
      "pattern": "^[a-z0-9-]+$"
    },
    "grandAlliance": {
      "type": "string",
      "enum": [
        "order",
        "chaos",
        "death",
        "destruction"
      ]
    },
    "points": {
      "type": "integer",
      "minimum": 0
    },
    "stats": {
      "type": "object",
      "properties": {
        "move": {
          "type": "string",
          "pattern": "^(-|(\\d*D6(\\+\\d+)?|\\d+)\")$"
        },
        "health": {
          "type": "integer",
          "minimum": 1
        },
        "save": {
          "type": "string",
          "pattern": "^\\d\\+$"
        },
        "control": {
          "type": "integer",
          "minimum": 0
        }
      },
      "required": [
        "move",
        "health",
        "save",
        "control"
      ],
      "additionalProperties": false
    },
    "role": {
      "type": "string",
      "enum": [
        "battleline",
        "other",
        "artillery",
        "behemoth"
      ]
    },
    "keywords": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "regimentKeywords": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "baseSize": {
      "type": "integer",
      "minimum": 1
    },
    "maxSize": {
      "type": "integer",
      "minimum": 1
    },
    "canReinforce": {
      "type": "boolean"
    },
    "constraintModifiers": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "constraintId": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [
              "set",
              "increment",
              "decrement"
            ]
          },
          "value": {
            "type": "string"
          },
          "repeats": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "value": {
                  "type": "string"
                },
                "repeats": {
                  "type": "string"
                },
                "field": {
                  "type": "string"
                },
                "scope": {
                  "type": "string"
                },
                "childId": {
                  "type": "string"
                },
                "shared": {
                  "type": "boolean"
                },
                "roundUp": {
                  "type": "boolean"
                },
                "includeChildSelections": {
                  "type": "boolean"
                },
                "includeChildForces": {
                  "type": "boolean"
                },
                "percentValue": {
                  "type": "boolean"
                }
              },
              "required": [
                "value",
                "repeats",
                "field",
                "scope"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "constraintId",
          "type",
          "value"
        ],
        "additionalProperties": false
      }
    },
    "isCollective": {
      "type": "boolean"
    },
    "costs": {
      "type": "object",
      "properties": {
        "destinyPoints": {
          "type": "integer",
          "minimum": 0
        },
        "ptgCategory": {
          "type": "integer",
          "minimum": 0
        },
        "ghbCategory": {
          "type": "integer",
          "minimum": 0
        }
      },
      "additionalProperties": false
    },
    "rules": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "description"
        ],
        "additionalProperties": false
      }
    },
    "publication": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "shortName": {
          "type": "string"
        },
        "page": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ],
      "additionalProperties": false
    },
    "weapons": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [
              "melee",
              "ranged"
            ]
          },
          "range": {
            "type": "string",
            "pattern": "^\\d+\"$"
          },
          "attacks": {
            "anyOf": [
              {
                "type": "integer",
                "minimum": 1
              },
              {
                "type": "string",
                "pattern": "^\\d?[dD]\\d+.*$"
              }
            ]
          },
          "hit": {
            "type": "string",
            "pattern": "^\\d\\+$"
          },
          "wound": {
            "type": "string",
            "pattern": "^\\d\\+$"
          },
          "rend": {
            "type": "integer",
            "minimum": 0,
            "maximum": 4
          },
          "damage": {
            "anyOf": [
              {
                "type": "integer",
                "minimum": 1
              },
              {
                "type": "string",
                "pattern": "^\\d?[dD]\\d+.*$"
              },
              {
                "type": "string",
                "pattern": "^⟝.*⟞$"
              }
            ]
          },
          "abilities": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "name",
          "type",
          "attacks",
          "hit",
          "wound",
          "rend",
          "damage"
        ],
        "additionalProperties": false
      }
    },
    "abilities": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [
              "passive",
              "reaction",
              "once-per-turn",
              "once-per-battle",
              "spell",
              "prayer",
              "command"
            ]
          },
          "phase": {
            "type": "string",
            "enum": [
              "any",
              "hero",
              "movement",
              "shooting",
              "charge",
              "combat",
              "end"
            ]
          },
          "castingValue": {
            "type": "integer",
            "minimum": 2,
            "maximum": 12
          },
          "chantingValue": {
            "type": "integer",
            "minimum": 2,
            "maximum": 6
          },
          "declare": {
            "type": "string"
          },
          "effect": {
            "type": "string"
          },
          "keywords": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "color": {
            "type": "string",
            "enum": [
              "Black",
              "Blue",
              "Gray",
              "Green",
              "Orange",
              "Purple",
              "Red",
              "Yellow"
            ]
          },
          "abilityCategory": {
            "type": "string",
            "enum": [
              "Offensive",
              "Defensive",
              "Movement",
              "Control",
              "Special",
              "Rallying",
              "Shooting"
            ]
          },
          "modifiers": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "enum": [
                    "set",
                    "increment",
                    "decrement",
                    "append",
                    "add",
                    "remove"
                  ]
                },
                "field": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                },
                "conditions": {
                  "type": "object",
                  "properties": {
                    "logic": {
                      "type": "string",
                      "enum": [
                        "and",
                        "or"
                      ]
                    },
                    "conditions": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "type": {
                            "type": "string",
                            "enum": [
                              "equalTo",
                              "notEqualTo",
                              "lessThan",
                              "greaterThan",
                              "atLeast",
                              "atMost",
                              "instanceOf"
                            ]
                          },
                          "value": {
                            "type": "string"
                          },
                          "field": {
                            "type": "string"
                          },
                          "scope": {
                            "type": "string"
                          },
                          "childId": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "type",
                          "value",
                          "field"
                        ],
                        "additionalProperties": false
                      }
                    },
                    "groups": {
                      "type": "array",
                      "items": {}
                    }
                  },
                  "required": [
                    "logic"
                  ],
                  "additionalProperties": false
                }
              },
              "required": [
                "type",
                "field",
                "value"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "name",
          "type",
          "effect"
        ],
        "additionalProperties": false
      }
    },
    "notes": {
      "type": "string"
    },
    "isWizard": {
      "anyOf": [
        {
          "type": "integer",
          "minimum": 1
        },
        {
          "type": "null"
        }
      ]
    },
    "isPriest": {
      "anyOf": [
        {
          "type": "integer",
          "minimum": 1
        },
        {
          "type": "null"
        }
      ]
    },
    "isUnique": {
      "type": "boolean"
    },
    "regimentAllows": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "keywords": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "keywords",
          "description"
        ],
        "additionalProperties": false
      }
    },
    "canJoinRegiment": {
      "anyOf": [
        {
          "type": "object",
          "properties": {
            "keywords": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "keywords"
          ],
          "additionalProperties": false
        },
        {
          "type": "null"
        }
      ]
    },
    "_meta": {
      "type": "object",
      "properties": {
        "lastUpdated": {
          "type": "string"
        },
        "source": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "id",
    "name",
    "faction",
    "points",
    "stats",
    "role",
    "keywords",
    "baseSize",
    "weapons",
    "isWizard",
    "isPriest",
    "isUnique",
    "canJoinRegiment"
  ],
  "additionalProperties": false
}

=== wargame-data/aos4/data/factions/cities-of-sigmar/heroes/doralia-ven-denst.json
{
  "$schema": "https://aos-data.org/schema/hero.schema.json",
  "id": "doralia-ven-denst",
  "name": "Doralia ven Denst",
  "faction": "cities-of-sigmar",
  "points": 0,
  "stats": {
    "move": "5\"",
    "health": 5,
    "save": "4+",
    "control": 2
  },
  "role": "other",
  "keywords": [
    "CITIES OF SIGMAR",
    "HERO",
    "HUMAN",
    "INFANTRY",
    "ORDER",
    "UNIQUE"
  ],
  "baseSize": 1,
  "weapons": [
    {
      "name": "Consecrated Blade",
      "type": "melee",
      "attacks": 3,
      "hit": "3+",
      "wound": "4+",
      "rend": 1,
      "damage": 2
    },
    {
      "name": "Anti‑thaumic Crossbow",
      "type": "ranged",
      "attacks": 2,
      "hit": "3+",
      "wound": "3+",
      "rend": 1,
      "damage": 2,
      "range": "18\"",
      "abilities": [
        "Anti‑**^^Wizard^^** (+1 Rend)"
      ]
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-07",
    "source": "BSData import"
  },
  "grandAlliance": "order",
  "regimentKeywords": [
    "CITIES OF SIGMAR",
    "HUMAN"
  ],
  "abilities": [
    {
      "name": "Weapons of Banishment",
      "type": "passive",
      "effect": "Double the Damage characteristic of this unit’s weapons for attacks that target **^^Wizards^^**, **^^Priests^^** and **^^Manifestations^^**.",
      "color": "Red",
      "abilityCategory": "Offensive"
    }
  ],
  "publication": {
    "name": "Faction Pack: Cities of Sigmar"
  },
  "isWizard": null,
  "isPriest": null,
  "isUnique": true,
  "canJoinRegiment": null
}

=== wargame-data/aos4/data/factions/ogor-mawtribes/heroes/huskard-on-stonehorn.json
{
  "$schema": "https://aos-data.org/schema/hero.schema.json",
  "id": "huskard-on-stonehorn",
  "name": "Huskard on Stonehorn",
  "faction": "ogor-mawtribes",
  "points": 300,
  "stats": {
    "move": "10\"",
    "health": 14,
    "save": "4+",
    "control": 10
  },
  "role": "other",
  "keywords": [
    "BEASTCLAW RAIDERS",
    "DESTRUCTION",
    "HERO",
    "MONSTER",
    "OGOR",
    "OGOR MAWTRIBES",
    "PRIEST (1)"
  ],
  "baseSize": 1,
  "weapons": [
    {
      "name": "Stonehorn’s Hooves",
      "type": "melee",
      "attacks": "D6",
      "hit": "4+",
      "wound": "2+",
      "rend": 1,
      "damage": "D3",
      "abilities": [
        "Companion"
      ]
    },
    {
      "name": "Punches and Kicks",
      "type": "melee",
      "attacks": 3,
      "hit": "4+",
      "wound": "2+",
      "rend": 0,
      "damage": 1
    },
    {
      "name": "Stonehorn’s Rock-hard Horns",
      "type": "melee",
      "attacks": 6,
      "hit": "4+",
      "wound": "2+",
      "rend": 2,
      "damage": 3,
      "abilities": [
        "Charge (+1 Damage)",
        "Companion"
      ]
    },
    {
      "name": "Harpoon Launcher",
      "type": "ranged",
      "attacks": 1,
      "hit": "4+",
      "wound": "3+",
      "rend": 1,
      "damage": "D3",
      "range": "18\""
    },
    {
      "name": "Chaintrap",
      "type": "ranged",
      "attacks": 1,
      "hit": "4+",
      "wound": "3+",
      "rend": 1,
      "damage": 3,
      "range": "12\"",
      "abilities": [
        "Anti‑**^^Monster^^** (+1 Rend)"
      ]
    },
    {
      "name": "Blood Vulture",
      "type": "ranged",
      "attacks": 1,
      "hit": "2+",
      "wound": "3+",
      "rend": 0,
      "damage": 1,
      "range": "24\""
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-08",
    "source": "BSData import"
  },
  "grandAlliance": "destruction",
  "regimentKeywords": [
    "BEASTCLAW RAIDERS",
    "OGOR",
    "OGOR MAWTRIBES",
    "PRIEST (1)"
  ],
  "abilities": [
    {
      "name": "Battle Damaged",
      "type": "passive",
      "effect": "While this unit has 10 or more damage points, the Attacks characteristic of its **Stonehorn’s Rock-hard Horns** is 4.",
      "color": "Black"
    },
    {
      "name": "Stone Skeleton",
      "type": "passive",
      "effect": "Ignore the first damage point that would be allocated to this unit in each phase.",
      "color": "Green",
      "abilityCategory": "Defensive"
    },
    {
      "name": "Everwinter's Goad",
      "type": "once-per-turn",
      "effect": "Roll a dice for each target. On a 3+:\n• If the target is a friendly **^^Ogor Mawtribes^^** unit, its **Companion** weapons have Crit (2 Hits) for the rest of the turn.\n• If the target is an enemy unit, subtract 1 from hit rolls for attacks made with its **Companion** weapons for the rest of the turn.",
      "phase": "combat",
      "declare": "Pick each friendly and enemy **^^Monster^^** within this unit’s combat range to be the targets.",
      "keywords": [
        "**^^RAMPAGE^^**"
      ],
      "color": "Red",
      "abilityCategory": "Special"
    }
  ],
  "publication": {
    "name": "2d6e-3ea2-52fe-a38"
  },
  "isWizard": null,
  "isPriest": 1,
  "isUnique": false,
  "canJoinRegiment": null
}

=== wargame-data/aos4/data/factions/nighthaunt/heroes/lord-vitriolic.json
{
  "$schema": "https://aos-data.org/schema/hero.schema.json",
  "id": "lord-vitriolic",
  "name": "Lord Vitriolic",
  "faction": "nighthaunt",
  "points": 120,
  "stats": {
    "move": "8\"",
    "health": 5,
    "save": "5+",
    "control": 2
  },
  "role": "other",
  "keywords": [
    "DEATH",
    "FLY",
    "HERO",
    "INFANTRY",
    "NIGHTHAUNT",
    "WARD (5+)"
  ],
  "baseSize": 1,
  "weapons": [
    {
      "name": "Hurled Vial",
      "type": "ranged",
      "attacks": 1,
      "hit": "3+",
      "wound": "3+",
      "rend": 2,
      "damage": "D6",
      "range": "10\"",
      "abilities": [
        "Crit (Auto-wound)"
      ]
    },
    {
      "name": "Culler's Sickle",
      "type": "melee",
      "attacks": 3,
      "hit": "4+",
      "wound": "3+",
      "rend": 1,
      "damage": "D3",
      "abilities": [
        "Crit (Auto-wound)"
      ]
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-07",
    "source": "BSData import"
  },
  "grandAlliance": "death",
  "regimentKeywords": [
    "FLY",
    "NIGHTHAUNT",
    "WARD (5+)"
  ],
  "abilities": [
    {
      "name": "Spectral Alchemy",
      "type": "once-per-turn",
      "effect": "Roll a dice. On a 3+, pick 1 of the following effects or roll two dice and apply both corresponding effects in an order of your choosing, including duplicate effects:\n**1 *Phantasmal Solvent:*** If the target has a Move characteristic of '-', inflict 6 mortal damage on the target.\n**2 *Acidic Fug:*** Inflict D3 mortal damage on the target.\n**3 *Fling Concoctions:** Add 1 to the Attacks characteristic of this unit's **Hurled Vial** this phase but all attacks made by this unit this phase must target that enemy unit.\n**4 *Choking Vapours:*** If the target is a **^^Wizard^^**, subtract 1 from its power level until the start of your next turn.\n**5 *Fear-laced Hallucinogen:*** If the target is a **^^Priest^^**, remove D3 ritual points from it.\n**6 *Unholy Prescription:*** Ward rolls cannot be made for the target for the rest of the turn.",
      "phase": "shooting",
      "declare": "Pick a visible enemy unit within 10\" of this unit to be the target.",
      "color": "Blue",
      "abilityCategory": "Special"
    }
  ],
  "isWizard": null,
  "isPriest": null,
  "isUnique": false,
  "canJoinRegiment": null
}

=== wargame-data/aos4/data/factions/flesh-eater-courts/heroes/ushoran-mortarch-of-delusion.json
{
  "$schema": "https://aos-data.org/schema/hero.schema.json",
  "id": "ushoran-mortarch-of-delusion",
  "name": "Ushoran, Mortarch of Delusion",
  "faction": "flesh-eater-courts",
  "points": 450,
  "stats": {
    "move": "10\"",
    "health": 16,
    "save": "4+",
    "control": 5
  },
  "role": "other",
  "keywords": [
    "ABHORRENT",
    "DEATH",
    "FLESH-EATER COURTS",
    "HERO",
    "MONSTER",
    "UNIQUE",
    "WARD (5+)",
    "WARMASTER",
    "WIZARD (2)"
  ],
  "baseSize": 1,
  "weapons": [
    {
      "name": "Sceptre of the Carrion King",
      "type": "melee",
      "attacks": 4,
      "hit": "3+",
      "wound": "2+",
      "rend": 2,
      "damage": "D3+3"
    },
    {
      "name": "Monstrous Talons",
      "type": "melee",
      "attacks": 8,
      "hit": "3+",
      "wound": "3+",
      "rend": 1,
      "damage": 2
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-07",
    "source": "BSData import"
  },
  "grandAlliance": "death",
  "regimentKeywords": [
    "ABHORRENT",
    "FLESH-EATER COURTS",
    "WARD (5+)",
    "WIZARD (2)"
  ],
  "abilities": [
    {
      "name": "Battle Damaged",
      "type": "passive",
      "effect": "While this unit has 10 or more damage points, the Attacks characteristic of its **Monstrous Talons** is 4.",
      "color": "Black"
    },
    {
      "name": "Shroudcage Fragment",
      "type": "once-per-turn",
      "effect": "Roll a dice for each target. If the roll exceeds the target’s Control characteristic, the target has **^^Strike-last^^** for the rest of the turn.",
      "phase": "combat",
      "declare": "Pick up to 3 enemy units in combat with this unit to be the targets.",
      "keywords": [
        "**^^RAMPAGE^^**"
      ],
      "color": "Red",
      "abilityCategory": "Defensive"
    },
    {
      "name": "Epicentre of Delusion",
      "type": "passive",
      "effect": "Each time you make a delusion roll, you can add 1 or subtract 1 from the roll.",
      "color": "Black",
      "abilityCategory": "Special"
    },
    {
      "name": "Glimpse of Delusion",
      "type": "spell",
      "effect": "Pick 1 of the target’s melee weapons. Immediately resolve combat attacks made with that weapon against the victim.",
      "phase": "hero",
      "declare": "Pick a visible enemy model within 18\" of this unit to be the target, pick another enemy unit that is visible to the target and within the target’s combat range to be the victim, then make a casting roll of 2D6. You can only pick the target's unit to be the victim if that unit has 2 or more models.",
      "castingValue": 7,
      "keywords": [
        "**^^SPELL^^**"
      ],
      "color": "Yellow",
      "abilityCategory": "Offensive"
    },
    {
      "name": "The One True King",
      "type": "passive",
      "effect": "While you believe this **^^Delusion^^**:\n• Add 1 to run rolls and charge rolls for friendly **^^Flesh-eater Courts^^** units.\n• Subtract 1 from run rolls and charge rolls for enemy units.\n• The melee weapons used by friendly **^^Serfs^^** units have **Anti-charge (+1 Rend)** while they are wholly within friendly territory and did not charge in the same turn.",
      "keywords": [
        "**^^DELUSION^^**"
      ],
      "color": "Black",
      "abilityCategory": "Special"
    }
  ],
  "isWizard": 2,
  "isPriest": null,
  "isUnique": true,
  "canJoinRegiment": null
}

=== wargame-data/aos4/data/factions/hedonites-of-slaanesh/heroes/glutos-orscollion-lord-of-gluttony.json
{
  "$schema": "https://aos-data.org/schema/hero.schema.json",
  "id": "glutos-orscollion-lord-of-gluttony",
  "name": "Glutos Orscollion, Lord of Gluttony",
  "faction": "hedonites-of-slaanesh",
  "points": 440,
  "stats": {
    "move": "8\"",
    "health": 18,
    "save": "4+",
    "control": 5
  },
  "role": "other",
  "keywords": [
    "CHAOS",
    "HEDONITES OF SLAANESH",
    "HERO",
    "SYBARITE",
    "UNIQUE",
    "WAR MACHINE",
    "WARD (5+)",
    "WARMASTER",
    "WIZARD (2)"
  ],
  "baseSize": 1,
  "weapons": [
    {
      "name": "Greatblade and Claws",
      "type": "melee",
      "attacks": 1,
      "hit": "3+",
      "wound": "4+",
      "rend": 0,
      "damage": 1,
      "abilities": [
        "Companion"
      ]
    },
    {
      "name": "Leerstave of Loth’shar",
      "type": "ranged",
      "attacks": 1,
      "hit": "2+",
      "wound": "4+",
      "rend": 0,
      "damage": 1,
      "range": "12\"",
      "abilities": [
        "Shoot in Combat"
      ]
    },
    {
      "name": "Scourge and Dagger",
      "type": "melee",
      "attacks": 1,
      "hit": "3+",
      "wound": "4+",
      "rend": 0,
      "damage": 1,
      "abilities": [
        "Companion"
      ]
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-06",
    "source": "BSData import"
  },
  "grandAlliance": "chaos",
  "regimentKeywords": [
    "HEDONITES OF SLAANESH",
    "SYBARITE",
    "WARD (5+)",
    "WIZARD (2)"
  ],
  "abilities": [
    {
      "name": "Gorge on Excess",
      "type": "passive",
      "effect": "**Heal (6)** the target.",
      "phase": "any",
      "declare": "Pick a friendly **^^Sybarite^^** unit wholly within 12\" of this unit to be the target."
    },
    {
      "name": "The Grand Gourmand",
      "type": "passive",
      "effect": "A different effect applies to friendly **^^Sybarite^^** units each battle round while they are wholly within 12\" of this unit, as shown below. The effects of all previous battle rounds also apply to those units while they are wholly within 12\" of this unit.\n**Battle Round 1:**\n***Starter:*** Add 1 to run rolls and charge rolls for those units.\n**Battle Round 2:**\n***Main:*** Add 3 to those units’ control scores.\n**Battle Round 3:**\n***Dessert:*** Add 1 to hit rolls for those unit’s attacks.\n**Battle Round 4+:**\n***Digestif:*** Add 1 to the Rend characteristic of those units’ melee weapons."
    },
    {
      "name": "Crippling Famishment",
      "type": "spell",
      "effect": "Until the start of your next turn:\n• Halve the target’s Move characteristic.\n• Halve run rolls and charge rolls for the target.",
      "phase": "hero",
      "declare": "Pick a visible enemy unit within 18\" of this unit to be the target, then make a casting roll of 2D6.",
      "castingValue": 7,
      "keywords": [
        "**^^SPELL^^**"
      ]
    },
    {
      "name": "Battle Damaged",
      "type": "passive",
      "effect": "While this unit has 10 or more damage points, the Attacks characteristic of its **Greatblade and Claws** is 6."
    }
  ],
  "isWizard": null,
  "isPriest": null,
  "isUnique": true,
  "canJoinRegiment": null
}

=== wargame-data/aos4/data/factions/cities-of-sigmar/heroes/battlemage-on-griffon.json
{
  "$schema": "https://aos-data.org/schema/hero.schema.json",
  "id": "battlemage-on-griffon",
  "name": "Battlemage on Griffon",
  "faction": "cities-of-sigmar",
  "points": 260,
  "stats": {
    "move": "12\"",
    "health": 15,
    "save": "4+",
    "control": 5
  },
  "role": "other",
  "keywords": [
    "CITIES OF SIGMAR",
    "FLY",
    "HERO",
    "HUMAN",
    "MONSTER",
    "ORDER",
    "WIZARD (1)"
  ],
  "baseSize": 1,
  "weapons": [
    {
      "name": "Amber Spear",
      "type": "ranged",
      "attacks": 3,
      "hit": "4+",
      "wound": "3+",
      "rend": 1,
      "damage": "D3",
      "range": "12\"",
      "abilities": [
        "Anti‑**^^Monster^^** (+1 Rend)"
      ]
    },
    {
      "name": "Beaststaff",
      "type": "melee",
      "attacks": 3,
      "hit": "4+",
      "wound": "3+",
      "rend": 1,
      "damage": "D3"
    },
    {
      "name": "Griffon’s Razor Claws and Twin Beaks",
      "type": "melee",
      "attacks": 6,
      "hit": "4+",
      "wound": "2+",
      "rend": 2,
      "damage": 3,
      "abilities": [
        "Companion"
      ]
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-07",
    "source": "BSData import"
  },
  "grandAlliance": "order",
  "regimentKeywords": [
    "CITIES OF SIGMAR",
    "FLY",
    "HUMAN",
    "WIZARD (1)"
  ],
  "abilities": [
    {
      "name": "Ghurish Ferocity",
      "type": "once-per-turn",
      "effect": "Roll a dice. On a 2+, add 1 to the Damage characteristic of this unit’s **Griffon’s Razor Claws and Twin Beaks** for attacks that target enemy **^^Monsters^^** for the rest of the turn.",
      "phase": "combat",
      "keywords": [
        "**^^RAMPAGE^^**"
      ],
      "color": "Red",
      "abilityCategory": "Offensive"
    },
    {
      "name": "Battle Damaged",
      "type": "passive",
      "effect": "While this unit has 10 or more damage points, the Attacks characteristic of its **Griffon’s Razor Claws and Twin Beaks** is 4.",
      "color": "Black"
    }
  ],
  "publication": {
    "name": "Faction Pack: Cities of Sigmar"
  },
  "isWizard": 1,
  "isPriest": null,
  "isUnique": false,
  "canJoinRegiment": null
}
