=== wargame-data/aos4/schema/hero.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://aos-data.org/schema/hero.schema.json",
  "title": "Hero",
  "description": "A hero warscroll for Age of Sigmar 4th Edition",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "id": {
      "type": "string",
      "pattern": "^[a-z0-9-]+$"
    },
    "name": {
      "type": "string"
    },
    "faction": {
      "type": "string",
      "pattern": "^[a-z0-9-]+$"
    },
    "grandAlliance": {
      "type": "string",
      "enum": [
        "order",
        "chaos",
        "death",
        "destruction"
      ]
    },
    "points": {
      "type": "integer",
      "minimum": 0
    },
    "stats": {
      "type": "object",
      "properties": {
        "move": {
          "type": "string",
          "pattern": "^(-|(\\d*D6(\\+\\d+)?|\\d+)\")$"
        },
        "health": {
          "type": "integer",
          "minimum": 1
        },
        "save": {
          "type": "string",
          "pattern": "^\\d\\+$"
        },
        "control": {
          "type": "integer",
          "minimum": 0
        }
      },
      "required": [
        "move",
        "health",
        "save",
        "control"
      ],
      "additionalProperties": false
    },
    "role": {
      "type": "string",
      "enum": [
        "battleline",
        "other",
        "artillery",
        "behemoth"
      ]
    },
    "keywords": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "regimentKeywords": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "baseSize": {
      "type": "integer",
      "minimum": 1
    },
    "maxSize": {
      "type": "integer",
      "minimum": 1
    },
    "canReinforce": {
      "type": "boolean"
    },
    "constraintModifiers": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "constraintId": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [
              "set",
              "increment",
              "decrement"
            ]
          },
          "value": {
            "type": "string"
          },
          "repeats": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "value": {
                  "type": "string"
                },
                "repeats": {
                  "type": "string"
                },
                "field": {
                  "type": "string"
                },
                "scope": {
                  "type": "string"
                },
                "childId": {
                  "type": "string"
                },
                "shared": {
                  "type": "boolean"
                },
                "roundUp": {
                  "type": "boolean"
                },
                "includeChildSelections": {
                  "type": "boolean"
                },
                "includeChildForces": {
                  "type": "boolean"
                },
                "percentValue": {
                  "type": "boolean"
                }
              },
              "required": [
                "value",
                "repeats",
                "field",
                "scope"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "constraintId",
          "type",
          "value"
        ],
        "additionalProperties": false
      }
    },
    "isCollective": {
      "type": "boolean"
    },
    "costs": {
      "type": "object",
      "properties": {
        "destinyPoints": {
          "type": "integer",
          "minimum": 0
        },
        "ptgCategory": {
          "type": "integer",
          "minimum": 0
        },
        "ghbCategory": {
          "type": "integer",
          "minimum": 0
        }
      },
      "additionalProperties": false
    },
    "rules": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "description"
        ],
        "additionalProperties": false
      }
    },
    "publication": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "shortName": {
          "type": "string"
        },
        "page": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ],
      "additionalProperties": false
    },
    "weapons": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [
              "melee",
              "ranged"
            ]
          },
          "range": {
            "type": "string",
            "pattern": "^\\d+\"$"
          },
          "attacks": {
            "anyOf": [
              {
                "type": "integer",
                "minimum": 1
              },
              {
                "type": "string",
                "pattern": "^\\d?[dD]\\d+.*$"
              }
            ]
          },
          "hit": {
            "type": "string",
            "pattern": "^\\d\\+$"
          },
          "wound": {
            "type": "string",
            "pattern": "^\\d\\+$"
          },
          "rend": {
            "type": "integer",
            "minimum": 0,
            "maximum": 4
          },
          "damage": {
            "anyOf": [
              {
                "type": "integer",
                "minimum": 1
              },
              {
                "type": "string",
                "pattern": "^\\d?[dD]\\d+.*$"
              },
              {
                "type": "string",
                "pattern": "^⟝.*⟞$"
              }
            ]
          },
          "abilities": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "name",
          "type",
          "attacks",
          "hit",
          "wound",
          "rend",
          "damage"
        ],
        "additionalProperties": false
      }
    },
    "abilities": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [
              "passive",
              "reaction",
              "once-per-turn",
              "once-per-battle",
              "spell",
              "prayer",
              "command"
            ]
          },
          "phase": {
            "type": "string",
            "enum": [
              "any",
              "hero",
              "movement",
              "shooting",
              "charge",
              "combat",
              "end"
            ]
          },
          "castingValue": {
            "type": "integer",
            "minimum": 2,
            "maximum": 12
          },
          "chantingValue": {
            "type": "integer",
            "minimum": 2,
            "maximum": 6
          },
          "declare": {
            "type": "string"
          },
          "effect": {
            "type": "string"
          },
          "keywords": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "color": {
            "type": "string",
            "enum": [
              "Black",
              "Blue",
              "Gray",
              "Green",
              "Orange",
              "Purple",
              "Red",
              "Yellow"
            ]
          },
          "abilityCategory": {
            "type": "string",
            "enum": [
              "Offensive",
              "Defensive",
              "Movement",
              "Control",
              "Special",
              "Rallying",
              "Shooting"
            ]
          },
          "modifiers": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "enum": [
                    "set",
                    "increment",
                    "decrement",
                    "append",
                    "add",
                    "remove"
                  ]
                },
                "field": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                },
                "conditions": {
                  "type": "object",
                  "properties": {
                    "logic": {
                      "type": "string",
                      "enum": [
                        "and",
                        "or"
                      ]
                    },
                    "conditions": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "type": {
                            "type": "string",
                            "enum": [
                              "equalTo",
                              "notEqualTo",
                              "lessThan",
                              "greaterThan",
                              "atLeast",
                              "atMost",
                              "instanceOf"
                            ]
                          },
                          "value": {
                            "type": "string"
                          },
                          "field": {
                            "type": "string"
                          },
                          "scope": {
                            "type": "string"
                          },
                          "childId": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "type",
                          "value",
                          "field"
                        ],
                        "additionalProperties": false
                      }
                    },
                    "groups": {
                      "type": "array",
                      "items": {}
                    }
                  },
                  "required": [
                    "logic"
                  ],
                  "additionalProperties": false
                }
              },
              "required": [
                "type",
                "field",
                "value"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "name",
          "type",
          "effect"
        ],
        "additionalProperties": false
      }
    },
    "notes": {
      "type": "string"
    },
    "isWizard": {
      "anyOf": [
        {
          "type": "integer",
          "minimum": 1
        },
        {
          "type": "null"
        }
      ]
    },
    "isPriest": {
      "anyOf": [
        {
          "type": "integer",
          "minimum": 1
        },
        {
          "type": "null"
        }
      ]
    },
    "isUnique": {
      "type": "boolean"
    },
    "regimentAllows": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "keywords": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "keywords",
          "description"
        ],
        "additionalProperties": false
      }
    },
    "canJoinRegiment": {
      "anyOf": [
        {
          "type": "object",
          "properties": {
            "keywords": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "keywords"
          ],
          "additionalProperties": false
        },
        {
          "type": "null"
        }
      ]
    },
    "_meta": {
      "type": "object",
      "properties": {
        "lastUpdated": {
          "type": "string"
        },
        "source": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "id",
    "name",
    "faction",
    "points",
    "stats",
    "role",
    "keywords",
    "baseSize",
    "weapons",
    "isWizard",
    "isPriest",
    "isUnique",
    "canJoinRegiment"
  ],
  "additionalProperties": false
}

=== wargame-data/aos4/data/factions/soulblight-gravelords/heroes/necromancer.json
{
  "$schema": "https://aos-data.org/schema/hero.schema.json",
  "id": "necromancer",
  "name": "Necromancer",
  "faction": "soulblight-gravelords",
  "points": 0,
  "stats": {
    "move": "5\"",
    "health": 5,
    "save": "6+",
    "control": 2
  },
  "role": "other",
  "keywords": [
    "DEATH",
    "HERO",
    "INFANTRY",
    "SOULBLIGHT GRAVELORDS",
    "WARD (6+)",
    "WIZARD (1)"
  ],
  "baseSize": 1,
  "weapons": [
    {
      "name": "Mortis Staff",
      "type": "melee",
      "attacks": 1,
      "hit": "4+",
      "wound": "4+",
      "rend": 0,
      "damage": 1
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-06",
    "source": "BSData import"
  },
  "grandAlliance": "death",
  "regimentKeywords": [
    "SOULBLIGHT GRAVELORDS",
    "WARD (6+)",
    "WIZARD (1)"
  ],
  "abilities": [
    {
      "name": "Vanhel's Danse Macabre",
      "type": "command",
      "effect": "The target can use 2 **^^Fight^^** abilities this phase. After the first is used, however, the target has **^^Strike-last^^** for the rest of the turn.",
      "phase": "combat",
      "declare": "Pick a friendly **^^Deathrattle^^ or **^^Deadwalkers^^** unit wholly within 12\" of this unit to be the target."
    },
    {
      "name": "Undead Minions",
      "type": "passive",
      "effect": "While this unit is within the combat range of a friendly **^^Deathrattle^^** or **^^Deadwalkers^^** unit:\n• This unit has **^^Ward (4+)^^**.\n• Each time you make a successful ward roll for this unit, allocate 1 damage point to a friendly **^^Deathrattle^^ or **^^Deadwalkers^^** unit within this unit’s combat range after the damage sequence for this unit has been resolved (ward rolls cannot be made for those damage points)."
    }
  ],
  "isWizard": null,
  "isPriest": null,
  "isUnique": false,
  "canJoinRegiment": null
}

=== wargame-data/aos4/data/factions/skaven/heroes/grey-seer.json
{
  "$schema": "https://aos-data.org/schema/hero.schema.json",
  "id": "grey-seer",
  "name": "Grey Seer",
  "faction": "skaven",
  "points": 120,
  "stats": {
    "move": "6\"",
    "health": 5,
    "save": "6+",
    "control": 2
  },
  "role": "other",
  "keywords": [
    "CHAOS",
    "HERO",
    "INFANTRY",
    "MASTERCLAN",
    "SKAVEN",
    "WIZARD (1)"
  ],
  "baseSize": 1,
  "weapons": [
    {
      "name": "Warpstone Staff",
      "type": "melee",
      "attacks": 1,
      "hit": "4+",
      "wound": "4+",
      "rend": 0,
      "damage": 1
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-06",
    "source": "BSData import"
  },
  "grandAlliance": "chaos",
  "regimentKeywords": [
    "MASTERCLAN",
    "SKAVEN",
    "WIZARD (1)"
  ],
  "abilities": [
    {
      "name": "Warpstone Shards",
      "type": "passive",
      "effect": "The next time you make a casting roll for this unit this phase, roll 3D6 instead of 2D6. This roll cannot be rerolled or modified.\nIf the casting roll is 13, the spell is successfully cast and cannot be unbound. After the effect of that spell has been resolved, inflict D3 mortal damage on this unit.\nIf the casting roll is not 13, remove 1 dice of your choice from the casting roll and use the remaining 2D6 as the casting roll.",
      "phase": "hero"
    }
  ],
  "isWizard": 1,
  "isPriest": null,
  "isUnique": false,
  "canJoinRegiment": null,
  "regimentAllows": [
    {
      "keywords": [
        "MASTERCLAN"
      ],
      "description": "Units with MASTERCLAN keyword"
    }
  ]
}

=== wargame-data/aos4/data/factions/slaves-to-darkness/heroes/ogroid-myrmidon.json
{
  "$schema": "https://aos-data.org/schema/hero.schema.json",
  "id": "ogroid-myrmidon",
  "name": "Ogroid Myrmidon",
  "faction": "slaves-to-darkness",
  "points": 120,
  "stats": {
    "move": "6\"",
    "health": 8,
    "save": "4+",
    "control": 2
  },
  "role": "other",
  "keywords": [
    "CHAOS",
    "HERO",
    "INFANTRY",
    "SLAVES TO DARKNESS"
  ],
  "baseSize": 1,
  "weapons": [
    {
      "name": "Gladiator Spear",
      "type": "melee",
      "attacks": 1,
      "hit": "3+",
      "wound": "4+",
      "rend": 0,
      "damage": 1,
      "abilities": [
        "Anti-**^^Monster^^** (+1 Rend)"
      ]
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-06",
    "source": "BSData import"
  },
  "grandAlliance": "chaos",
  "regimentKeywords": [
    "SLAVES TO DARKNESS"
  ],
  "abilities": [
    {
      "name": "Myrmidon Rage",
      "type": "passive",
      "effect": "While this unit is damaged, add 2 to the Attacks characteristic of its melee weapons."
    },
    {
      "name": "Pit Master",
      "type": "reaction",
      "effect": "Pick a friendly **Ogroid Theridons** unit that has not used a **^^Fight^^** ability this turn and is within this unit’s combat range to be the target. The target can be picked to use a **^^Fight^^** ability immediately after the **^^Fight^^** ability used by this unit has been resolved. If it is picked to do so, add 1 to hit rolls for the target’s attacks for the rest of the turn."
    }
  ],
  "isWizard": null,
  "isPriest": null,
  "isUnique": false,
  "canJoinRegiment": null
}

=== wargame-data/aos4/data/factions/gloomspite-gitz/heroes/snarlboss.json
{
  "$schema": "https://aos-data.org/schema/hero.schema.json",
  "id": "snarlboss",
  "name": "Snarlboss",
  "faction": "gloomspite-gitz",
  "points": 120,
  "stats": {
    "move": "12\"",
    "health": 5,
    "save": "5+",
    "control": 2
  },
  "role": "other",
  "keywords": [
    "CAVALRY",
    "DESTRUCTION",
    "GITMOB",
    "GLOOMSPITE GITZ",
    "HERO"
  ],
  "baseSize": 1,
  "weapons": [
    {
      "name": "Snarlfang's Slavering Jaws",
      "type": "melee",
      "attacks": 1,
      "hit": "4+",
      "wound": "4+",
      "rend": 0,
      "damage": 1,
      "abilities": [
        "Companion"
      ]
    },
    {
      "name": "Boss Loppa",
      "type": "melee",
      "attacks": 1,
      "hit": "4+",
      "wound": "4+",
      "rend": 0,
      "damage": 1
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-07",
    "source": "BSData import"
  },
  "grandAlliance": "destruction",
  "regimentKeywords": [
    "GITMOB",
    "GLOOMSPITE GITZ"
  ],
  "abilities": [
    {
      "name": "Vicious Snarls and Great Howls",
      "type": "once-per-turn",
      "effect": "For the rest of the turn, add 1 to the Attacks characteristic of the targets' **Companion** melee weapons.",
      "phase": "combat",
      "declare": "If this unit charged this turn, pick this unit and up to 2 friendly **^^Gitmob Cavalry^^** units within this unit's combat range to be the targets.",
      "color": "Red",
      "abilityCategory": "Offensive"
    },
    {
      "name": "Boss Snarlfang",
      "type": "passive",
      "effect": "Add 2 to charge rolls for friendly **^^Gitmob Cavalry^^** units while they are wholly within 12\" of this unit.",
      "color": "Orange",
      "abilityCategory": "Movement"
    }
  ],
  "publication": {
    "name": "Battletome: Gloomspite Gitz"
  },
  "isWizard": null,
  "isPriest": null,
  "isUnique": false,
  "canJoinRegiment": null
}

=== wargame-data/aos4/data/factions/flesh-eater-courts/heroes/crypt-haunter-courtier.json
{
  "$schema": "https://aos-data.org/schema/hero.schema.json",
  "id": "crypt-haunter-courtier",
  "name": "Crypt Haunter Courtier",
  "faction": "flesh-eater-courts",
  "points": 120,
  "stats": {
    "move": "7\"",
    "health": 6,
    "save": "5+",
    "control": 2
  },
  "role": "other",
  "keywords": [
    "DEATH",
    "FLESH-EATER COURTS",
    "HERO",
    "INFANTRY",
    "NOBLE",
    "WARD (6+)"
  ],
  "baseSize": 1,
  "weapons": [
    {
      "name": "Massive Bone Club and Rancid Talons",
      "type": "melee",
      "attacks": 5,
      "hit": "4+",
      "wound": "3+",
      "rend": 2,
      "damage": 3
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-07",
    "source": "BSData import"
  },
  "grandAlliance": "death",
  "regimentKeywords": [
    "FLESH-EATER COURTS",
    "NOBLE",
    "WARD (6+)"
  ],
  "abilities": [
    {
      "name": "Knightly Exemplar",
      "type": "reaction",
      "effect": "Pick a friendly **Crypt Horrors** unit that has not used a **^^Fight^^** ability this turn and is within this unit’s combat range to be the target. The target can be picked to use a **^^Fight^^** ability immediately after the **^^Fight^^** ability used by this unit has been resolved. If it is picked to do so, add 1 to hit rolls for the target’s attacks for the rest of the turn.",
      "color": "Red",
      "abilityCategory": "Offensive"
    },
    {
      "name": "Blessed Blood",
      "type": "passive",
      "effect": "Heal (D3) this unit.",
      "phase": "hero",
      "color": "Yellow",
      "abilityCategory": "Defensive"
    }
  ],
  "isWizard": null,
  "isPriest": null,
  "isUnique": false,
  "canJoinRegiment": null
}

=== wargame-data/aos4/data/factions/kruleboyz/heroes/killaboss-with-stab-grot.json
{
  "$schema": "https://aos-data.org/schema/hero.schema.json",
  "id": "killaboss-with-stab-grot",
  "name": "Killaboss with Stab-grot",
  "faction": "kruleboyz",
  "points": 80,
  "stats": {
    "move": "5\"",
    "health": 6,
    "save": "4+",
    "control": 2
  },
  "role": "other",
  "keywords": [
    "DESTRUCTION",
    "HERO",
    "INFANTRY",
    "KRULEBOYZ"
  ],
  "baseSize": 1,
  "weapons": [
    {
      "name": "Boss-hacka",
      "type": "melee",
      "attacks": 1,
      "hit": "4+",
      "wound": "4+",
      "rend": 0,
      "damage": 1,
      "abilities": [
        "Crit (Mortal)"
      ]
    },
    {
      "name": "Stab-grot’s Shiv",
      "type": "melee",
      "attacks": 1,
      "hit": "4+",
      "wound": "4+",
      "rend": 0,
      "damage": 1,
      "abilities": [
        "Crit (Mortal)",
        "Companion"
      ]
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-06",
    "source": "BSData import"
  },
  "grandAlliance": "destruction",
  "regimentKeywords": [
    "KRULEBOYZ"
  ],
  "abilities": [
    {
      "name": "Keep 'Em in Line",
      "type": "reaction",
      "effect": "If this unit is wholly within 12\" of the unit using the ‘All-out Attack’ command, add 1 to wound rolls for combat attacks made by that unit for the rest of the phase.",
      "color": "Red",
      "abilityCategory": "Offensive"
    },
    {
      "name": "Unleash the Stab-grot!",
      "type": "once-per-battle",
      "effect": "Pick 1 of the following effects:\n• Pick an enemy unit in combat with this unit to be the target. Inflict D3 mortal damage on the target.\n• This unit has **^^Ward (5+)^^** for the rest of the turn.\nAfter resolving either effect, remove this unit’s **Stab-grot** from the battlefield.",
      "phase": "combat",
      "color": "Red",
      "abilityCategory": "Special"
    },
    {
      "name": "Stab-grot",
      "type": "passive",
      "effect": "This unit’s **Stab-grot** is a token. If this unit’s **Stab grot** has been removed, it can no longer attack with its **Stab-grot’s Shiv** and it cannot use the ‘Unleash the Stab-grot!’ ability.",
      "color": "Black",
      "abilityCategory": "Special"
    }
  ],
  "publication": {
    "name": "Battletome: Orruk Warclans"
  },
  "isWizard": null,
  "isPriest": null,
  "isUnique": false,
  "canJoinRegiment": null
}

=== wargame-data/aos4/data/factions/helsmiths-of-hashut/heroes/daemonsmith-on-infernal-taurus.json
{
  "$schema": "https://aos-data.org/schema/hero.schema.json",
  "id": "daemonsmith-on-infernal-taurus",
  "name": "Daemonsmith on Infernal Taurus",
  "faction": "helsmiths-of-hashut",
  "points": 290,
  "stats": {
    "move": "10\"",
    "health": 15,
    "save": "3+",
    "control": 5
  },
  "role": "other",
  "keywords": [
    "CHAOS",
    "DUARDIN",
    "FLY",
    "HELSMITHS OF HASHUT",
    "HERO",
    "MONSTER",
    "WAR MACHINE",
    "WIZARD (1)"
  ],
  "baseSize": 1,
  "weapons": [
    {
      "name": "Infernal Staff",
      "type": "melee",
      "attacks": 3,
      "hit": "4+",
      "wound": "3+",
      "rend": 1,
      "damage": "D3"
    },
    {
      "name": "Hurled Daemonfire",
      "type": "ranged",
      "attacks": 3,
      "hit": "4+",
      "wound": "4+",
      "rend": 1,
      "damage": "D3",
      "range": "18\"",
      "abilities": [
        "Crit (2 Hits)",
        "Shoot in Combat"
      ]
    },
    {
      "name": "Horns and Hooves",
      "type": "melee",
      "attacks": 6,
      "hit": "4+",
      "wound": "2+",
      "rend": 2,
      "damage": 3,
      "abilities": [
        "Charge (+1 Damage)",
        "Companion"
      ]
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-08",
    "source": "BSData import"
  },
  "grandAlliance": "chaos",
  "regimentKeywords": [
    "DUARDIN",
    "FLY",
    "HELSMITHS OF HASHUT",
    "WIZARD (1)"
  ],
  "abilities": [
    {
      "name": "Unholy Stampede",
      "type": "passive",
      "effect": "While a friendly **^^Helsmiths of Hashut Cavalry^^** unit is wholly within 12\" of this unit:\n• That unit can use a **^^Retreat^^** ability and still use **^^Charge^^** abilities later in the turn.\n• No mortal damage is inflicted on that unit by **^^Retreat^^** abilities.",
      "color": "Black",
      "abilityCategory": "Special"
    },
    {
      "name": "Battle Damaged",
      "type": "passive",
      "effect": "While this unit has 10 or more damage points, the Attacks characteristic of its **Horns and Hooves** is 4.",
      "color": "Black"
    },
    {
      "name": "Immolating Presence",
      "type": "once-per-turn",
      "effect": "Roll a dice. If the roll exceeds the target's Health characteristic, 1 model in the target unit is slain.",
      "phase": "any",
      "declare": "Pick an enemy unit in combat with this unit to be the target.",
      "keywords": [
        "**^^RAMPAGE^^**"
      ],
      "color": "Purple",
      "abilityCategory": "Offensive"
    },
    {
      "name": "Daemonic Resilience",
      "type": "passive",
      "effect": "Apply the effect below that corresponds with the number of **daemonic power points** this unit has:\n**1** This unit has **^^Ward (6+)^^**.\n**2** This unit has **^^Ward (5+)^^**.\n**3** This unit has **^^Ward (4+)^^** against damage inflicted by **^^Spells^^**, **^^Prayers^^**, and abilites used by **^^Manifestations^^**. Otherwise, it has **^^Ward (5+)^^**.",
      "color": "Green",
      "abilityCategory": "Defensive"
    }
  ],
  "publication": {
    "name": "Battletome: Helsmiths of Hashut"
  },
  "isWizard": 1,
  "isPriest": null,
  "isUnique": false,
  "canJoinRegiment": null
}
