=== wargame-data/aos4/schema/lore.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://aos-data.org/schema/lore.schema.json",
  "title": "Lore",
  "description": "A spell lore, prayer lore, or manifestation lore for Age of Sigmar",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "id": {
      "type": "string",
      "pattern": "^[a-z0-9-]+$"
    },
    "name": {
      "type": "string"
    },
    "loreType": {
      "type": "string",
      "enum": [
        "spell",
        "prayer",
        "manifestation"
      ]
    },
    "factionId": {
      "type": "string",
      "pattern": "^[a-z0-9-]+$"
    },
    "spells": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "castingValue": {
            "type": "integer",
            "minimum": 2,
            "maximum": 12
          },
          "timing": {
            "type": "string"
          },
          "declare": {
            "type": "string"
          },
          "effect": {
            "type": "string"
          },
          "keywords": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "color": {
            "type": "string",
            "enum": [
              "Black",
              "Blue",
              "Gray",
              "Green",
              "Orange",
              "Purple",
              "Red",
              "Yellow"
            ]
          },
          "abilityCategory": {
            "type": "string",
            "enum": [
              "Offensive",
              "Defensive",
              "Movement",
              "Control",
              "Special",
              "Rallying",
              "Shooting"
            ]
          }
        },
        "required": [
          "name",
          "castingValue",
          "effect"
        ],
        "additionalProperties": false
      }
    },
    "prayers": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "chantingValue": {
            "type": "integer",
            "minimum": 2,
            "maximum": 12
          },
          "timing": {
            "type": "string"
          },
          "declare": {
            "type": "string"
          },
          "effect": {
            "type": "string"
          },
          "keywords": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "color": {
            "type": "string",
            "enum": [
              "Black",
              "Blue",
              "Gray",
              "Green",
              "Orange",
              "Purple",
              "Red",
              "Yellow"
            ]
          },
          "abilityCategory": {
            "type": "string",
            "enum": [
              "Offensive",
              "Defensive",
              "Movement",
              "Control",
              "Special",
              "Rallying",
              "Shooting"
            ]
          }
        },
        "required": [
          "name",
          "chantingValue",
          "effect"
        ],
        "additionalProperties": false
      }
    },
    "_meta": {
      "type": "object",
      "properties": {
        "lastUpdated": {
          "type": "string"
        },
        "source": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "id",
    "name",
    "loreType"
  ],
  "additionalProperties": false
}

=== wargame-data/aos4/data/_shared/lores/lore-of-the-storm.json
{
  "$schema": "https://aos-data.org/schema/lore.schema.json",
  "id": "lore-of-the-storm",
  "name": "Lore of the Storm",
  "loreType": "spell",
  "_meta": {
    "lastUpdated": "2026-01-06",
    "source": "BSData import"
  },
  "spells": [
    {
      "name": "Lightning Blast",
      "castingValue": 5,
      "timing": "Your Hero Phase",
      "effect": "Inflict D3 mortal damage on the target.",
      "keywords": [
        "**^^SPELL^^**",
        "**^^UNLIMITED^^**"
      ],
      "declare": "Pick a friendly **^^Stormcast Eternals Wizard^^** to cast this spell, then pick the closest visible enemy unit to them that has not been picked to be the target of this ability this turn to be the target. If 2 or more visible enemy units are tied to be the closest, you can pick which is the target. Then, make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Offensive"
    },
    {
      "name": "Starfall",
      "castingValue": 7,
      "timing": "Your Hero Phase",
      "effect": "Until the start of your next turn, subtract 1 from the number of dice rolled when making charge rolls for the target, to a minimum of 1.",
      "keywords": [
        "**^^SPELL^^**"
      ],
      "declare": "Pick a friendly **^^Stormcast Eternals Wizard^^** to cast this spell, pick a visible enemy **^^Infantry^^** or **^^Cavalry^^** unit within 18\" of them to be the target, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Movement"
    },
    {
      "name": "Thundershock",
      "castingValue": 6,
      "timing": "Your Hero Phase",
      "effect": "Subtract 1 from wound rolls for the target’s attacks until the start of your next turn.",
      "keywords": [
        "**^^SPELL^^**"
      ],
      "declare": "Pick a friendly **^^Stormcast Eternals Wizard^^** to cast this spell, picka visible enemy unit within 12\" of them to be the target, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Defensive"
    }
  ]
}

=== wargame-data/aos4/data/_shared/lores/manifestations-of-doom.json
{
  "$schema": "https://aos-data.org/schema/lore.schema.json",
  "id": "manifestations-of-doom",
  "name": "Manifestations of Doom",
  "loreType": "manifestation",
  "_meta": {
    "lastUpdated": "2026-01-07",
    "source": "BSData import"
  },
  "spells": [
    {
      "name": "Summon Bell of Doom",
      "castingValue": 7,
      "timing": "Your Hero Phase",
      "effect": "Set up a **Bell of Doom** wholly within 13\" of the caster, visible to them and more than 9\" from all enemy units.",
      "keywords": [
        "**^^SPELL^^**",
        "**^^SUMMON^^**"
      ],
      "declare": "If there is not a friendly **Bell of Doom** on the battlefield, pick a friendly **^^Skaven Wizard^^** to cast this spell, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Special"
    },
    {
      "name": "Summon Vermintide",
      "castingValue": 7,
      "timing": "Your Hero Phase",
      "effect": "Set up a **Vermintide** wholly within 13\" of the caster, visible to them and more than 9\" from all enemy units.",
      "keywords": [
        "**^^SPELL^^**",
        "**^^SUMMON^^**"
      ],
      "declare": "If there is not a friendly **Vermintide** on the battlefield, pick a friendly **^^Skaven Wizard^^** to cast this spell, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Special"
    },
    {
      "name": "Summon Warp Lightning Vortex",
      "castingValue": 7,
      "timing": "Your Hero Phase",
      "effect": "Set up the first part of the **Warp Lightning Vortex** within 18\" of the caster and visible to them, then set up the second and third parts exactly 7\" from the first part and exactly 7\" from each other so that they form a triangle.",
      "keywords": [
        "**^^SPELL^^**",
        "**^^SUMMON^^**"
      ],
      "declare": "If there is not a friendly **Warp Lightning Vortex** on the battlefield, pick a friendly **^^Skaven Wizard^^** to cast this spell, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Special"
    }
  ]
}

=== wargame-data/aos4/data/_shared/lores/lore-of-the-deeps.json
{
  "$schema": "https://aos-data.org/schema/lore.schema.json",
  "id": "lore-of-the-deeps",
  "name": "Lore of the Deeps",
  "loreType": "spell",
  "_meta": {
    "lastUpdated": "2026-01-06",
    "source": "BSData import"
  },
  "spells": [
    {
      "name": "Counter-current",
      "castingValue": 7,
      "timing": "Your Hero Phase",
      "effect": "Until the start of your next turn, halve run rolls and charge rolls for the target.",
      "keywords": [
        "**^^SPELL^^**"
      ],
      "declare": "Pick a friendly **^^Idoneth Deepkin Wizard^^** to cast this spell, pick a visible enemy unit within 18\" of them to be the target, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Movement"
    },
    {
      "name": "Pressure of the Deep",
      "castingValue": 7,
      "timing": "Your Hero Phase",
      "effect": "Roll a dice for each model in the target unit. For each 5+, inflict 1 mortal damage on the target.",
      "keywords": [
        "**^^SPELL^^**"
      ],
      "declare": "Pick a friendly **^^Idoneth Deepkin Wizard^^** to cast this spell, pick a visible enemy unit within 18\" of them to be the target, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Offensive"
    },
    {
      "name": "Steed of Tides",
      "castingValue": 6,
      "timing": "Your Hero Phase",
      "effect": "Remove the target from the battlefield and set it up again on the battlefield more than 9\" from all enemy units.",
      "keywords": [
        "**^^SPELL^^**",
        "**^^UNLIMITED^^**"
      ],
      "declare": "Pick a friendly **^^Idoneth Deepkin Wizard^^** to cast this spell, pick a visible friendly **^^Idoneth Deepkin^^** unit wholly within 12\" of them and not in combat to be the target, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Movement"
    }
  ]
}

=== wargame-data/aos4/data/lores/manifestations/bestial-manifestations.json
{
  "$schema": "https://aos-data.org/schema/lore.schema.json",
  "id": "bestial-manifestations",
  "name": "Bestial Manifestations",
  "loreType": "manifestation",
  "_meta": {
    "lastUpdated": "2026-01-08",
    "source": "BSData import"
  },
  "spells": [
    {
      "name": "Summon Doomblast Dirgehorn",
      "castingValue": 6,
      "timing": "Your Hero Phase",
      "effect": "Set up a **Doomblast Dirgehorn** wholly within 18\" of the chanter.",
      "keywords": [
        "**^^SPELL^^**",
        "**^^SUMMON^^**"
      ],
      "declare": "If there is not a friendly **Doomblast Dirgehorn** on the battlefield, pick a friendly **^^Beasts of Chaos Wizard^^** to cast this spell, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Special"
    },
    {
      "name": "Summon Ravening Direflock",
      "castingValue": 7,
      "timing": "Your Hero Phase",
      "effect": "Set up a **Ravening Direflock** wholly within 18\" of the caster and more than 9\" from all enemy units. A **Ravening Direflock** has 3 parts that must each be set up within 1\" of at least 1 other part.",
      "keywords": [
        "**^^SPELL^^**",
        "**^^SUMMON^^**"
      ],
      "declare": "If there is not a friendly **Ravening Direflock** on the battlefield, pick a friendly **^^Beasts of Chaos Wizard^^** to cast this spell, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Special"
    },
    {
      "name": "Summon Wildfire Taurus",
      "castingValue": 7,
      "timing": "Your Hero Phase",
      "effect": "Set up a **Wildfire Taurus** wholly within 18\" of the caster and more than 9\" from all enemy units.",
      "keywords": [
        "**^^SPELL^^**",
        "**^^SUMMON^^**"
      ],
      "declare": "If there is not a friendly **Wildfire Taurus** on the battlefield, pick a friendly **^^Beasts of Chaos Wizard^^** to cast this spell, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Special"
    }
  ]
}

=== wargame-data/aos4/data/_shared/lores/lore-of-undeath.json
{
  "$schema": "https://aos-data.org/schema/lore.schema.json",
  "id": "lore-of-undeath",
  "name": "Lore of Undeath",
  "loreType": "spell",
  "_meta": {
    "lastUpdated": "2026-01-08",
    "source": "BSData import"
  },
  "spells": [
    {
      "name": "Prison of Grief",
      "castingValue": 7,
      "timing": "Your Hero Phase",
      "effect": "The target has **^^Strike-last^^** until the start of your next turn.",
      "keywords": [
        "**^^SPELL^^**"
      ],
      "declare": "Pick a friendly **^^Soulblight Gravelords Wizard^^** to cast this spell, pick a visible enemy unit within 12\" of them to be the target, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Defensive"
    },
    {
      "name": "Vile Transference",
      "castingValue": 7,
      "timing": "Your Hero Phase",
      "effect": "Roll a number of dice equal to the number of models in the target unit. For each 6, inflict 1 mortal damage on that unit. If any enemy models were slain by this spell, **Heal(D3)** the caster.",
      "keywords": [
        "**^^SPELL^^**",
        "**^^UNLIMITED^^**"
      ],
      "declare": "Pick a friendly **^^Soulblight Gravelord Wizard^^** to cast this spell, pick a visible enemy unit within 18\" of them to be the target, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Special"
    },
    {
      "name": "Waste Away",
      "castingValue": 7,
      "timing": "Your Hero Phase",
      "effect": "For the rest of the turn, subtract 1 from the Damage characteristic of the target’s melee weapons.",
      "keywords": [
        "**^^SPELL^^**"
      ],
      "declare": "Pick a friendly **^^Soulblight Gravelords Wizard^^** to cast this spell, pick a visible enemy unit within 12\" of them to be the target, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Defensive"
    }
  ]
}

=== wargame-data/aos4/data/lores/manifestations/manifestation-lore-knights-of-the-crimson-keep.json
{
  "$schema": "https://wargamedata.com/aos4/schema/lore.schema.json",
  "id": "manifestation-lore-knights-of-the-crimson-keep",
  "name": "Manifestation Lore: Knights of the Crimson Keep",
  "loreType": "manifestation",
  "_meta": {
    "lastUpdated": "2026-01-08",
    "source": "BSData import"
  },
  "spells": [
    {
      "name": "Summon Unholy Reliquary",
      "castingValue": 6,
      "timing": "Your Hero Phase",
      "effect": "Set up a **Unholy Reliquary** endless spell wholly within 18\" of the caster.",
      "keywords": [
        "**^^SPELL^^**",
        "**^^SUMMON^^**"
      ],
      "declare": "If there is not a friendly **Unholy Reliquary** on the battlefield, pick a friendly **^^Soulblight Gravelords Wizard^^** to cast this spell, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Special"
    }
  ]
}

=== wargame-data/aos4/data/lores/spells/spell-lore-the-eternal-nightmare.json
{
  "$schema": "https://wargamedata.com/aos4/schema/lore.schema.json",
  "id": "spell-lore-the-eternal-nightmare",
  "name": "Spell Lore: The Eternal Nightmare",
  "loreType": "spell",
  "_meta": {
    "lastUpdated": "2026-01-08",
    "source": "BSData import"
  },
  "spells": [
    {
      "name": "Divine Terror",
      "castingValue": 5,
      "timing": "Your Hero Phase",
      "effect": "Subtract 3 from the target's control score for the rest of the turn.",
      "keywords": [
        "**^^SPELL^^**",
        "**^^UNLIMITED^^**"
      ],
      "declare": "Pick a friendly **^^Eternal Nightmare Wizard^^** to cast this spell, pick a visible enemy unit within 18\" of them to be the target, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Control"
    },
    {
      "name": "The Will of Nagash",
      "castingValue": 8,
      "timing": "Your Hero Phase",
      "effect": "Until the start of your next turn, if the unmodified hit roll or unmodified wound roll for an attack that targets thet arget unit is 1-3, the attack fails and the attack sequence ends.",
      "keywords": [
        "**^^SPELL^^**"
      ],
      "declare": "Pick a friendly **^^Eternal Nightmare Wizard^^** to cast this spell, pick a visible friendly **^^Eternal Nightmare Infantry^^** unit wholly within 12\" of them to be the target, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Defensive"
    }
  ]
}

=== wargame-data/aos4/data/lores/spells/spell-lore-astral-templars.json
{
  "$schema": "https://wargamedata.com/aos4/schema/lore.schema.json",
  "id": "spell-lore-astral-templars",
  "name": "Spell Lore: Astral Templars",
  "loreType": "spell",
  "_meta": {
    "lastUpdated": "2026-01-08",
    "source": "BSData import"
  },
  "spells": [
    {
      "name": "Primal Blizzard",
      "castingValue": 6,
      "timing": "Your Hero Phase",
      "effect": "Roll a dice for each model in the target unit. For each 6, inflict 1 mortal damage on the target.",
      "keywords": [
        "**^^SPELL^^**",
        "**^^UNLIMITED^^**"
      ],
      "declare": "Pick a friendly **^^Astral Templars Wizard^^** to cast this spell, pick a visible enemy unit within 18\" of them to be the target, then make a casting roll of 2D6."
    },
    {
      "name": "Hunter's Wings",
      "castingValue": 6,
      "timing": "Your Hero Phase",
      "effect": "Until the start of your next turn:\n• Add 3 to the target's Move characteristic.\n• Subtract 1 from hit rolls and wound rolls for shooting attacks that target the target unit.",
      "keywords": [
        "**^^SPELL^^**",
        "**^^UNLIMITED^^**"
      ],
      "declare": "Pick a friendly **^^Astral Templars Wizard^^** to cast this spell, pick a visible friendly unit wholly within 12\" of them to be the target, then make a casting roll of 2D6."
    }
  ]
}
