=== wargame-data/aos4/schema/lore.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://aos-data.org/schema/lore.schema.json",
  "title": "Lore",
  "description": "A spell lore, prayer lore, or manifestation lore for Age of Sigmar",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "id": {
      "type": "string",
      "pattern": "^[a-z0-9-]+$"
    },
    "name": {
      "type": "string"
    },
    "loreType": {
      "type": "string",
      "enum": [
        "spell",
        "prayer",
        "manifestation"
      ]
    },
    "factionId": {
      "type": "string",
      "pattern": "^[a-z0-9-]+$"
    },
    "spells": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "castingValue": {
            "type": "integer",
            "minimum": 2,
            "maximum": 12
          },
          "timing": {
            "type": "string"
          },
          "declare": {
            "type": "string"
          },
          "effect": {
            "type": "string"
          },
          "keywords": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "color": {
            "type": "string",
            "enum": [
              "Black",
              "Blue",
              "Gray",
              "Green",
              "Orange",
              "Purple",
              "Red",
              "Yellow"
            ]
          },
          "abilityCategory": {
            "type": "string",
            "enum": [
              "Offensive",
              "Defensive",
              "Movement",
              "Control",
              "Special",
              "Rallying",
              "Shooting"
            ]
          }
        },
        "required": [
          "name",
          "castingValue",
          "effect"
        ],
        "additionalProperties": false
      }
    },
    "prayers": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "chantingValue": {
            "type": "integer",
            "minimum": 2,
            "maximum": 12
          },
          "timing": {
            "type": "string"
          },
          "declare": {
            "type": "string"
          },
          "effect": {
            "type": "string"
          },
          "keywords": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "color": {
            "type": "string",
            "enum": [
              "Black",
              "Blue",
              "Gray",
              "Green",
              "Orange",
              "Purple",
              "Red",
              "Yellow"
            ]
          },
          "abilityCategory": {
            "type": "string",
            "enum": [
              "Offensive",
              "Defensive",
              "Movement",
              "Control",
              "Special",
              "Rallying",
              "Shooting"
            ]
          }
        },
        "required": [
          "name",
          "chantingValue",
          "effect"
        ],
        "additionalProperties": false
      }
    },
    "_meta": {
      "type": "object",
      "properties": {
        "lastUpdated": {
          "type": "string"
        },
        "source": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "id",
    "name",
    "loreType"
  ],
  "additionalProperties": false
}

=== wargame-data/aos4/data/_shared/lores/manifestation-lore-draconith-skywing.json
{
  "$schema": "https://aos-data.org/schema/lore.schema.json",
  "id": "manifestation-lore-draconith-skywing",
  "name": "Manifestation Lore: Draconith Skywing",
  "loreType": "manifestation",
  "_meta": {
    "lastUpdated": "2026-01-06",
    "source": "BSData import"
  },
  "spells": [
    {
      "name": "Summon Everblaze Comet",
      "castingValue": 8,
      "timing": "Your Hero Phase",
      "effect": "Set up an **Everblaze Comet** wholly within 18\" of the caster.",
      "keywords": [
        "**^^SPELL^^**",
        "**^^SUMMON^^**"
      ],
      "declare": "If there is not a friendly **Everblaze Comet** on the battlefield, pick a friendly **^^Stormcast Eternals Wizard^^** to cast this spell, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Special"
    }
  ]
}

=== wargame-data/aos4/data/lores/prayers/prayers-of-the-khainite-cult.json
{
  "$schema": "https://wargamedata.com/aos4/schema/lore.schema.json",
  "id": "prayers-of-the-khainite-cult",
  "name": "Prayers of the Khainite Cult",
  "loreType": "prayer",
  "_meta": {
    "lastUpdated": "2026-01-08",
    "source": "BSData import"
  },
  "prayers": [
    {
      "name": "Sacrament of Blood",
      "chantingValue": 5,
      "timing": "Your Hero Phase",
      "effect": "Until the start of your next turn, add 1 to the current battle round number when determining which effects of the ‘Blood Rites’ ability apply to the target. If the chanting roll was 10+, until the start of your next turn, treat the current battle round number as 5 when determining which effects of the ‘Blood Rites’ ability apply to the target instead.",
      "keywords": [
        "**^^PRAYER^^**",
        "**^^UNLIMITED^^**"
      ],
      "declare": "Pick a friendly **^^Daughters of Khaine Priest^^** to chant this prayer, pick a visible friendly **^^Daughters of Khaine^^** unit wholly within 12\" of them to be the target, then make a chanting roll of D6.",
      "color": "Yellow",
      "abilityCategory": "Offensive"
    },
    {
      "name": "Covenant of the Iron Heart",
      "chantingValue": 4,
      "timing": "Your Hero Phase",
      "effect": "Ignore negative modifiers to the target’s control score until the start of your next turn. In addition, if the chanting roll was 8+, add 5 to the target’s control score until the start of your next turn.",
      "keywords": [
        "**^^PRAYER^^**"
      ],
      "declare": "Pick a friendly **^^Daughters of Khaine Priest^^** to chant this prayer, pick a visible friendly **^^Daughters of Khaine^^** unit wholly within 12\" of them to be the target, then make a chanting roll of D6.",
      "color": "Yellow",
      "abilityCategory": "Control"
    },
    {
      "name": "Martyr's Sacrifice",
      "chantingValue": 4,
      "timing": "Your Hero Phase",
      "effect": "Until the start of your next turn, each time a model in the target unit is slain by a combat attack, before removing the model from play, pick an enemy unit in combat with the target and roll a dice. If the chanting roll was 8+, roll 2 dice instead of 1. For each 5+, inflict 1 mortal damage on that enemy unit after the **^^Fight^^** ability has been resolved.",
      "keywords": [
        "**^^PRAYER^^**"
      ],
      "declare": "Pick a friendly **^^Daughters of Khaine Priest^^** to chant this prayer, pick a visible friendly **^^Daughters of Khaine^^** unit wholly within 12\" of them to be the target, then make a chanting roll of D6.",
      "color": "Yellow",
      "abilityCategory": "Offensive"
    }
  ]
}

=== wargame-data/aos4/data/lores/spells/lore-of-frazzlegit.json
{
  "$schema": "https://wargamedata.com/aos4/schema/lore.schema.json",
  "id": "lore-of-frazzlegit",
  "name": "Lore of Frazzlegit",
  "loreType": "spell",
  "_meta": {
    "lastUpdated": "2026-01-08",
    "source": "BSData import"
  },
  "spells": [
    {
      "name": "Gitspeed",
      "castingValue": 6,
      "timing": "Your Hero Phase",
      "effect": "Until the start of your next turn, add 2\" to the Move characteristic of friendly non-**^^Troggoth Gloomspite Gitz^^** units while they are wholly within 12\" of this unit.",
      "keywords": [
        "**^^SPELL^^**"
      ],
      "declare": "Pick a friendly **^^Gloomspite Gitz Wizard^^** to cast this spell, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Movement"
    },
    {
      "name": "Bright Fright",
      "castingValue": 6,
      "timing": "Your Hero Phase",
      "effect": "Each target can immediately use a **^^Retreat^^** ability as if it was your movement phase. No mortal damage is inflicted on the targets by those **^^Retreat^^** abilities.",
      "keywords": [
        "**^^SPELL^^**",
        "**^^UNLIMITED^^**"
      ],
      "declare": "Pick a friendly **^^Gloomspite Gitz Wizard^^** to cast this spell, pick up to 3 friendly visible **^^Gloomspite Gitz^^** units wholly within 12\" of them to be the targets, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Movement"
    },
    {
      "name": "Gaze of Glareface",
      "castingValue": 6,
      "timing": "Your Hero Phase",
      "effect": "Until the start of your next turn:\n• The target cannot use **^^Run^^** abilities.\n• Halve the Range characteristic of the target’s ranged weapons.",
      "keywords": [
        "**^^SPELL^^**"
      ],
      "declare": "Pick a friendly **^^Gloomspite Gitz^^** Wizard to cast this spell, pick a visible enemy unit within 18\" of them to be the target, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Defensive"
    }
  ]
}

=== wargame-data/aos4/data/_shared/lores/prayer-lore-draconith-skywing.json
{
  "$schema": "https://aos-data.org/schema/lore.schema.json",
  "id": "prayer-lore-draconith-skywing",
  "name": "Prayer Lore: Draconith Skywing",
  "loreType": "prayer",
  "_meta": {
    "lastUpdated": "2026-01-06",
    "source": "BSData import"
  },
  "prayers": [
    {
      "name": "Sanctification",
      "chantingValue": 4,
      "timing": "Your Hero Phase",
      "effect": "Until the start of your next turn, subtract 1 from casting rolls for enemy **^^Wizards^^** while they are within 30\" of the chanter. If the chanting roll was 12+, subtract 1 from casting rolls for enemy **^^Wizards^^** for the rest of the battle and friendly **^^Priests^^** cannot use this ability again for the rest of the battle.",
      "keywords": [
        "**^^PRAYER^^**"
      ],
      "declare": "Pick a friendly **^^Draconith Skywing Priest^^** to chant this prayer, then make a chanting roll of D6.",
      "color": "Yellow",
      "abilityCategory": "Special"
    },
    {
      "name": "Sigmar's Grace",
      "chantingValue": 4,
      "timing": "Your Hero Phase",
      "effect": "**Heal (D3)** the target. If the chanting roll was 8+, **Heal (2D3)** the target instead.",
      "keywords": [
        "**^^PRAYER^^**",
        "**^^UNLIMITED^^**"
      ],
      "declare": "Pick a friendly **^^Draconith Skywing Priest^^** to chant this prayer, pick a friendly **^^Draconith Skywing^^** unit wholly within 12\" of them to be the target, then make a chanting roll of D6.",
      "color": "Yellow",
      "abilityCategory": "Defensive"
    }
  ]
}

=== wargame-data/aos4/data/_shared/lores/spell-lore-petrifex-elite.json
{
  "$schema": "https://aos-data.org/schema/lore.schema.json",
  "id": "spell-lore-petrifex-elite",
  "name": "Spell Lore: Petrifex Elite",
  "loreType": "spell",
  "_meta": {
    "lastUpdated": "2026-01-06",
    "source": "BSData import"
  },
  "spells": [
    {
      "name": "Hard as Diamond",
      "castingValue": 7,
      "timing": "Your Hero Phase",
      "effect": "Subtract 1 from wound rolls for attacks that target that unit until the start of your next turn.",
      "keywords": [
        "**^^SPELL^^**",
        "**^^UNLIMITED^^**"
      ],
      "declare": "Pick a friendly **^^Petrifex Elite Wizard^^** to cast this spell, pick a visible friendly unit wholly within 12\" of them to be the target, then make a casting roll of 2D6."
    },
    {
      "name": "Skeletal Grasp",
      "castingValue": 8,
      "timing": "Your Hero Phase",
      "effect": "Until the start of your next turn:\n• Halve the target's Move characteristic\n• Subtract 1 from the number of dice rolled when making charge rolls for the target, to a minimum of 1.",
      "keywords": [
        "**^^SPELL^^**"
      ],
      "declare": "Pick a friendly **^^Petrifex Elite Wizard^^** to cast this spell, pick a visible enemy unit within 12\" of them to be the target, then make a casting roll of 2D6."
    },
    {
      "name": "Tremors From the Entombed",
      "castingValue": 7,
      "timing": "Your Hero Phase",
      "effect": "If the target is a terrain feature, roll a D3 for each unit (friendly or enemy) within 3\" of it. On a 2+. inflict an amount of mortal damage on that unit equal to the roll.\nIf the unit is a faction terrain feature, inflict 2D6 mortal damage on it, If the target is destroyed, before removing it from play, roll a D3 for each unit (friendly or enemy) within 3\" of it. On a 2+, inflict an amount of mortal damage on that unit equal to the roll.",
      "keywords": [
        "**^^SPELL^^**"
      ],
      "declare": "Pick a friendly **^^Petrifex Elite Wizard^^** to cast this spell, pick a terrain feature or faction terrain feature within 12\" of them to be the target, then make a casting roll of 2D6."
    }
  ]
}

=== wargame-data/aos4/data/_shared/lores/lore-of-primal-jungles.json
{
  "$schema": "https://aos-data.org/schema/lore.schema.json",
  "id": "lore-of-primal-jungles",
  "name": "Lore of Primal Jungles",
  "loreType": "spell",
  "_meta": {
    "lastUpdated": "2026-01-06",
    "source": "BSData import"
  },
  "spells": [
    {
      "name": "Empowered Celestite",
      "castingValue": 7,
      "timing": "Your Hero Phase",
      "effect": "Add 1 to the Rend characteristic of the target’s melee weapons for the rest of the turn.",
      "keywords": [
        "**^^SPELL^^**"
      ],
      "declare": "Pick a friendly **^^Seraphon Wizard^^** to cast this spell, pick a visible friendly **^^Saurus^^** unit wholly within 12\" of them to be the target, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Offensive"
    },
    {
      "name": "Light of Chotec",
      "castingValue": 6,
      "timing": "Your Hero Phase",
      "effect": "Roll a number of dice equal to the number of damage points the target has. For each 4+, **Heal (1)** the target.",
      "keywords": [
        "**^^SPELL^^**",
        "**^^UNLIMITED^^**"
      ],
      "declare": "Pick a friendly **^^Seraphon Wizard^^** to cast this spell, pick a visible friendly **^^Seraphon^^** unit wholly within 12\" of them to be the target, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Defensive"
    },
    {
      "name": "The Earth Trembles",
      "castingValue": 8,
      "timing": "Your Hero Phase",
      "effect": "Draw a straight line between the target point and the closest part on the caster’s base. Roll a D3 for each unit (friendly and enemy) that has models passed across by this line. On a 2+, inflict an amount of mortal damage on that unit equal to the roll.",
      "keywords": [
        "**^^SPELL^^**"
      ],
      "declare": "Pick a friendly **^^Seraphon Wizard^^** to cast this spell, pick a point on the battlefield within 18\" of them to be the target point, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Offensive"
    }
  ]
}

=== wargame-data/aos4/data/lores/prayers/prayers-of-the-stormhosts.json
{
  "$schema": "https://wargamedata.com/aos4/schema/lore.schema.json",
  "id": "prayers-of-the-stormhosts",
  "name": "Prayers of the Stormhosts",
  "loreType": "prayer",
  "_meta": {
    "lastUpdated": "2026-01-08",
    "source": "BSData import"
  },
  "prayers": [
    {
      "name": "Bless Weapons",
      "chantingValue": 6,
      "timing": "Your Hero Phase",
      "effect": "Add 1 to the Attacks characteristic of the target’s melee weapons until the start of your next turn. If the chanting roll was 12+, this ability affects all visible friendly **^^Stormcast Eternals^^** units wholly within 12\" of the chanter.",
      "keywords": [
        "**^^PRAYER^^**"
      ],
      "declare": "Pick a friendly **^^Stormcast Eternals Priest^^** to chant this prayer, pick a visible friendly **^^Stormcast Eternals Infantry^^** unit wholly within 12\" of them to be the target, then make a chanting roll of D6.",
      "color": "Yellow",
      "abilityCategory": "Offensive"
    },
    {
      "name": "Translocation",
      "chantingValue": 4,
      "timing": "Your Hero Phase",
      "effect": "Remove the target from the battlefield and set it up again on the battlefield more than 9\" from all enemy units. In addition, if the chanting roll was 8+, subtract 1 from hit rolls for attacks that target that unit for the rest of the battle round.",
      "keywords": [
        "**^^PRAYER^^**"
      ],
      "declare": "Pick a friendly **^^Stormcast Eternals Priest^^** to chant this prayer, pick a visible friendly **^^Stormcast Eternals^^** unit wholly within 12\" of them to be the target, then make a chanting roll of D6.",
      "color": "Yellow",
      "abilityCategory": "Movement"
    },
    {
      "name": "Healing Storm",
      "chantingValue": 4,
      "timing": "Your Hero Phase",
      "effect": "Heal (D3) the target. If the chanting roll was 8+, **Heal (D3)** each visible friendly **^^Stormcast Eternals^^** unit wholly within 12\" of the chanter instead.",
      "keywords": [
        "**^^PRAYER^^**",
        "**^^UNLIMITED^^**"
      ],
      "declare": "Pick a friendly **^^Stormcast Eternals Priest^^** to chant this prayer, pick a visible friendly **^^Stormcast Eternals^^** unit wholly within 12\" of them to be the target, then make a chanting roll of D6.",
      "color": "Yellow",
      "abilityCategory": "Defensive"
    }
  ]
}

=== wargame-data/aos4/data/lores/spells/manifestation-lore-big-waaagh.json
{
  "$schema": "https://aos-data.org/schema/lore.schema.json",
  "id": "manifestation-lore-big-waaagh",
  "name": "Manifestation Lore: Big Waaagh!",
  "loreType": "spell",
  "_meta": {
    "lastUpdated": "2026-01-08",
    "source": "BSData import"
  },
  "spells": [
    {
      "name": "Summon Foot of Gork",
      "castingValue": 7,
      "timing": "Your Hero Phase",
      "effect": "Set up a **Foot of Gork** wholly within 12\" of the caster, visible to them and more than 9\" from all enemy units. A **Foot of Gork** has 2 parts that must be set up within 9\" of each other.",
      "keywords": [
        "**^^SPELL^^**",
        "**^^SUMMON^^**"
      ],
      "declare": "If there is not a friendly **Foot of Gork** on the battlefield, pick a friendly **^^Kruleboyz Wizard^^** to cast this spell, then make a casting roll of 2D6.",
      "color": "Yellow",
      "abilityCategory": "Special"
    }
  ]
}
