=== wargame-data/aos4/schema/regiment-of-renown.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://aos-data.org/schema/regiment-of-renown.schema.json",
  "title": "Regiment of Renown",
  "description": "A Regiment of Renown for Age of Sigmar 4th Edition",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "id": {
      "type": "string",
      "pattern": "^[a-z0-9-]+$"
    },
    "name": {
      "type": "string"
    },
    "points": {
      "type": "integer",
      "minimum": 0
    },
    "allowedFactions": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "units": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "count": {
            "type": "integer",
            "minimum": 1
          },
          "required": {
            "type": "boolean"
          }
        },
        "required": [
          "name",
          "count"
        ],
        "additionalProperties": false
      }
    },
    "abilities": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [
              "passive",
              "reaction",
              "once-per-turn",
              "once-per-battle",
              "spell",
              "prayer",
              "command"
            ]
          },
          "phase": {
            "type": "string",
            "enum": [
              "any",
              "hero",
              "movement",
              "shooting",
              "charge",
              "combat",
              "end"
            ]
          },
          "castingValue": {
            "type": "integer",
            "minimum": 2,
            "maximum": 12
          },
          "chantingValue": {
            "type": "integer",
            "minimum": 2,
            "maximum": 6
          },
          "declare": {
            "type": "string"
          },
          "effect": {
            "type": "string"
          },
          "keywords": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "color": {
            "type": "string",
            "enum": [
              "Black",
              "Blue",
              "Gray",
              "Green",
              "Orange",
              "Purple",
              "Red",
              "Yellow"
            ]
          },
          "abilityCategory": {
            "type": "string",
            "enum": [
              "Offensive",
              "Defensive",
              "Movement",
              "Control",
              "Special",
              "Rallying",
              "Shooting"
            ]
          },
          "modifiers": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "enum": [
                    "set",
                    "increment",
                    "decrement",
                    "append",
                    "add",
                    "remove"
                  ]
                },
                "field": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                },
                "conditions": {
                  "type": "object",
                  "properties": {
                    "logic": {
                      "type": "string",
                      "enum": [
                        "and",
                        "or"
                      ]
                    },
                    "conditions": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "type": {
                            "type": "string",
                            "enum": [
                              "equalTo",
                              "notEqualTo",
                              "lessThan",
                              "greaterThan",
                              "atLeast",
                              "atMost",
                              "instanceOf"
                            ]
                          },
                          "value": {
                            "type": "string"
                          },
                          "field": {
                            "type": "string"
                          },
                          "scope": {
                            "type": "string"
                          },
                          "childId": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "type",
                          "value",
                          "field"
                        ],
                        "additionalProperties": false
                      }
                    },
                    "groups": {
                      "type": "array",
                      "items": {}
                    }
                  },
                  "required": [
                    "logic"
                  ],
                  "additionalProperties": false
                }
              },
              "required": [
                "type",
                "field",
                "value"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "name",
          "type",
          "effect"
        ],
        "additionalProperties": false
      }
    },
    "_meta": {
      "type": "object",
      "properties": {
        "lastUpdated": {
          "type": "string"
        },
        "source": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "id",
    "name",
    "points",
    "allowedFactions",
    "units"
  ],
  "additionalProperties": false
}

=== wargame-data/aos4/data/_shared/regiments-of-renown/exile-scavengers.json
{
  "$schema": "https://aos-data.org/schema/regiment-of-renown.schema.json",
  "id": "exile-scavengers",
  "name": "Exile Scavengers",
  "points": 410,
  "allowedFactions": [
    "Beasts of Chaos [LEGENDS]",
    "Bonesplitterz [LEGENDS]",
    "Cities of Sigmar",
    "Daughters of Khaine",
    "Fyreslayers",
    "Gloomspite Gitz",
    "Ironjawz",
    "Kruleboyz",
    "Lumineth Realm-lords",
    "Ogor Mawtribes",
    "Ossiarch Bonereapers",
    "Seraphon",
    "Slaves to Darkness",
    "Slaves to Darkness - Legion of the First Prince",
    "Sons of Behemat",
    "Soulblight Gravelords"
  ],
  "units": [
    {
      "name": "Skywardens",
      "count": 1,
      "required": true
    },
    {
      "name": "Grundstok Gunhauler",
      "count": 1,
      "required": true
    },
    {
      "name": "Endrinmaster with Dirigible Suit",
      "count": 1,
      "required": true
    }
  ],
  "abilities": [
    {
      "name": "An Eye for Loot",
      "type": "passive",
      "effect": "Set up the units in this Regiment of Renown in reserve studying the battlefield. They have now been deployed.",
      "declare": "This ability must be used to deploy this Regiment of Renown.",
      "keywords": [
        "**^^DEPLOY^^**"
      ],
      "color": "Black",
      "abilityCategory": "Special"
    },
    {
      "name": "Swoop In",
      "type": "passive",
      "effect": "Set up the **Grundstok Gunhauler** on the battlefield more than 6\" from all enemy units that have an artefact of power and more than 9\" from all other enemy units. Then, set up all other units in this Regiment of Renown wholly within 3\" of the **Grundstok Gunhauler** and more than 6\" from all enemy units.",
      "phase": "movement",
      "declare": "Pick the **Grundstok Gunhauler** in this Regiment of Renown to use this ability if it is studying the battlefield.",
      "color": "Gray",
      "abilityCategory": "Movement"
    },
    {
      "name": "'What's Yours is Mine'",
      "type": "once-per-turn",
      "effect": "Roll a dice. Add 1 to the roll for each unit in this Regiment of Renown that is in combat with the target. On a 6+, the target no longer has that artefact of power.",
      "phase": "combat",
      "declare": "Pick an enemy unit in combat with a unit in this Regiment of Renown to be the target. Then, pick an artefact of power the target has.",
      "color": "Red",
      "abilityCategory": "Special"
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-08",
    "source": "BSData import"
  }
}

=== wargame-data/aos4/data/_shared/regiments-of-renown/elthwins-thorns.json
{
  "$schema": "https://aos-data.org/schema/regiment-of-renown.schema.json",
  "id": "elthwins-thorns",
  "name": "Elthwin's Thorns",
  "points": 220,
  "allowedFactions": [
    "Cities of Sigmar",
    "Daughters of Khaine",
    "Fyreslayers",
    "Idoneth Deepkin",
    "Kharadron Overlords",
    "Lumineth Realm-lords",
    "Seraphon",
    "Stormcast Eternals"
  ],
  "units": [
    {
      "name": "Gossamid Archers",
      "count": 1,
      "required": true
    },
    {
      "name": "Arch-Revenant",
      "count": 1,
      "required": true
    }
  ],
  "abilities": [
    {
      "name": "Gossamid Champion",
      "type": "passive",
      "effect": "Until the start of your next turn, subtract X from charge rolls for the target, where X is the number of damage points allocated to the target this phase by shooting attacks made by the **Gossamid Archers** unit in the Regiment of Renown, to a maximum of 6.",
      "phase": "shooting",
      "declare": "Pick the **Arch-Revenant** in this Regiment of Renown to use this ability, the pick a visible enemy unit within 12\" of them to be the target.",
      "color": "Blue",
      "abilityCategory": "Shooting"
    },
    {
      "name": "Flight of the Zephyrspites",
      "type": "once-per-turn",
      "effect": "If both units in this Regiment of Renown are within each other’s combat range and neither unit is in combat, roll a dice. On a 3+, remove both units from the battlefield, then set them up again within each other’s combat range, wholly within 3\" of a terrain feature and more than 9\" from all enemy units.",
      "phase": "shooting",
      "color": "Blue",
      "abilityCategory": "Shooting"
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-07",
    "source": "BSData import"
  }
}
