=== wargame-data/aos4/schema/terrain.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://wargamedata.com/aos4/schema/terrain.schema.json",
  "title": "Terrain",
  "description": "A faction terrain feature for Age of Sigmar",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "id": {
      "type": "string",
      "pattern": "^(warscroll|spell|prayer|enhancement|terrain|formation|manifestation)\\.[a-z0-9_]+\\.[a-z0-9_]+$"
    },
    "bsdataId": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "const": "terrain"
    },
    "name": {
      "type": "string"
    },
    "faction": {
      "type": "string"
    },
    "grandAlliance": {
      "type": "string",
      "enum": [
        "order",
        "chaos",
        "death",
        "destruction"
      ]
    },
    "keywords": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "stats": {
      "type": "object",
      "properties": {
        "move": {
          "type": "string",
          "pattern": "^(-|(\\d*D6(\\+\\d+)?|\\d+)\")$"
        },
        "health": {
          "type": "integer",
          "minimum": 1
        },
        "save": {
          "type": "string",
          "pattern": "^\\d\\+$"
        },
        "control": {
          "anyOf": [
            {
              "type": "integer",
              "minimum": 0
            },
            {
              "type": "string",
              "const": "-"
            }
          ]
        }
      },
      "required": [
        "move",
        "health",
        "save",
        "control"
      ],
      "additionalProperties": false
    },
    "abilities": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [
              "passive",
              "reaction",
              "once-per-turn",
              "once-per-battle",
              "spell",
              "prayer",
              "command"
            ]
          },
          "phase": {
            "type": "string",
            "enum": [
              "any",
              "hero",
              "movement",
              "shooting",
              "charge",
              "combat",
              "end"
            ]
          },
          "castingValue": {
            "type": "integer",
            "minimum": 2,
            "maximum": 12
          },
          "chantingValue": {
            "type": "integer",
            "minimum": 2,
            "maximum": 6
          },
          "declare": {
            "type": "string"
          },
          "effect": {
            "type": "string"
          },
          "keywords": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "color": {
            "type": "string",
            "enum": [
              "Black",
              "Blue",
              "Gray",
              "Green",
              "Orange",
              "Purple",
              "Red",
              "Yellow"
            ]
          },
          "abilityCategory": {
            "type": "string",
            "enum": [
              "Offensive",
              "Defensive",
              "Movement",
              "Control",
              "Special",
              "Rallying",
              "Shooting"
            ]
          },
          "modifiers": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "enum": [
                    "set",
                    "increment",
                    "decrement",
                    "append",
                    "add",
                    "remove"
                  ]
                },
                "field": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                },
                "conditions": {
                  "type": "object",
                  "properties": {
                    "logic": {
                      "type": "string",
                      "enum": [
                        "and",
                        "or"
                      ]
                    },
                    "conditions": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "type": {
                            "type": "string",
                            "enum": [
                              "equalTo",
                              "notEqualTo",
                              "lessThan",
                              "greaterThan",
                              "atLeast",
                              "atMost",
                              "instanceOf"
                            ]
                          },
                          "value": {
                            "type": "string"
                          },
                          "field": {
                            "type": "string"
                          },
                          "scope": {
                            "type": "string"
                          },
                          "childId": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "type",
                          "value",
                          "field"
                        ],
                        "additionalProperties": false
                      }
                    },
                    "groups": {
                      "type": "array",
                      "items": {}
                    }
                  },
                  "required": [
                    "logic"
                  ],
                  "additionalProperties": false
                }
              },
              "required": [
                "type",
                "field",
                "value"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "name",
          "type",
          "effect"
        ],
        "additionalProperties": false
      }
    },
    "_meta": {
      "type": "object",
      "properties": {
        "lastUpdated": {
          "type": "string"
        },
        "source": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "id",
    "bsdataId",
    "type",
    "name",
    "faction",
    "keywords",
    "stats",
    "abilities"
  ],
  "additionalProperties": false
}

=== wargame-data/aos4/data/catalog/terrain/seraphon/realmshaper_engine.json
{
  "$schema": "https://wargamedata.com/aos4/schema/terrain.schema.json",
  "id": "terrain.seraphon.realmshaper_engine",
  "bsdataId": "dbb9-da98-e92e-b31e",
  "type": "terrain",
  "name": "Realmshaper Engine",
  "faction": "seraphon",
  "keywords": [
    "faction terrain",
    "order",
    "faction:seraphon"
  ],
  "stats": {
    "move": "-",
    "health": 15,
    "save": "4+",
    "control": "-"
  },
  "abilities": [
    {
      "name": "Fierce Guardians",
      "type": "passive",
      "effect": "Add 1 to hit rolls for combat attacks made by friendly **^^Saurus^^** or **^^Kroxigor^^** units that target an enemy unit while that enemy unit is within 9\" of this terrain feature.",
      "color": "Red",
      "abilityCategory": "Offensive"
    },
    {
      "name": "Power Unleashed",
      "type": "once-per-turn",
      "effect": "Roll a D3 for each target. On a 2+, inflict an amount of mortal damage on the target equal to the roll. If that terrain feature has a Health characteristic, inflict D3 mortal damage on it.",
      "phase": "hero",
      "declare": "If there are any friendly **^^Seraphon Wizards^^** within 3\" of this terrain feature, pick another terrain feature within 24\" of this terrain feature, then pick up to 3 enemy units within 3\" of that terrain feature to be the targets.",
      "color": "Yellow",
      "abilityCategory": "Offensive"
    }
  ],
  "_meta": {
    "lastUpdated": "2026-01-09",
    "source": "BSData import"
  },
  "grandAlliance": "order"
}
